// Code generated by cmd/codegen; DO NOT EDIT.

package decodo

// AirbnbParams contains parameters for the airbnb target.
type AirbnbParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool   `json:"markdown,omitempty"`
	URL      *string `json:"url,omitempty"`
	XHR      *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AirbnbParams) GetTarget() string { return string(p.Target) }

// NewAirbnbParams creates a new AirbnbParams with the target pre-set.
func NewAirbnbParams() *AirbnbParams {
	return &AirbnbParams{Target: TargetAirbnb}
}

// AmazonParams contains parameters for the amazon target.
type AmazonParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless  *string `json:"headless,omitempty"`
	Markdown  *bool   `json:"markdown,omitempty"`
	Parse     *bool   `json:"parse,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	URL       *string `json:"url,omitempty"`
	XHR       *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonParams) GetTarget() string { return string(p.Target) }

// NewAmazonParams creates a new AmazonParams with the target pre-set.
func NewAmazonParams() *AmazonParams {
	return &AmazonParams{Target: TargetAmazon}
}

// AmazonBestsellersParams contains parameters for the amazon_bestsellers target.
type AmazonBestsellersParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Category    *string `json:"category,omitempty"`
	Currency    *string `json:"currency,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Domain      *string `json:"domain,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	Markdown    *bool   `json:"markdown,omitempty"`
	PageFrom    *int    `json:"page_from,omitempty"`
	Parse       *bool   `json:"parse,omitempty"`
	Query       *string `json:"query,omitempty"`
	SessionID   *string `json:"session_id,omitempty"`
	XHR         *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonBestsellersParams) GetTarget() string { return string(p.Target) }

// NewAmazonBestsellersParams creates a new AmazonBestsellersParams with the target pre-set.
func NewAmazonBestsellersParams() *AmazonBestsellersParams {
	return &AmazonBestsellersParams{Target: TargetAmazonBestsellers}
}

// AmazonPricingParams contains parameters for the amazon_pricing target.
type AmazonPricingParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Currency    *string `json:"currency,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Domain      *string `json:"domain,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless  *string `json:"headless,omitempty"`
	Markdown  *bool   `json:"markdown,omitempty"`
	PageFrom  *int    `json:"page_from,omitempty"`
	Parse     *bool   `json:"parse,omitempty"`
	Query     *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	XHR       *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonPricingParams) GetTarget() string { return string(p.Target) }

// NewAmazonPricingParams creates a new AmazonPricingParams with the target pre-set.
func NewAmazonPricingParams() *AmazonPricingParams {
	return &AmazonPricingParams{Target: TargetAmazonPricing}
}

// AmazonProductParams contains parameters for the amazon_product target.
type AmazonProductParams struct {
	Target            Target  `json:"target"`
	AutoselectVariant *bool   `json:"autoselect_variant,omitempty"`
	CallbackURL       *string `json:"callback_url,omitempty"`
	Currency          *string `json:"currency,omitempty"`
	DeviceType        *string `json:"device_type,omitempty"`
	Domain            *string `json:"domain,omitempty"`
	Geo               *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless  *string `json:"headless,omitempty"`
	Markdown  *bool   `json:"markdown,omitempty"`
	Parse     *bool   `json:"parse,omitempty"`
	Query     *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	XHR       *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonProductParams) GetTarget() string { return string(p.Target) }

// NewAmazonProductParams creates a new AmazonProductParams with the target pre-set.
func NewAmazonProductParams() *AmazonProductParams {
	return &AmazonProductParams{Target: TargetAmazonProduct}
}

// AmazonSearchParams contains parameters for the amazon_search target.
type AmazonSearchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Category    *string `json:"category,omitempty"`
	Currency    *string `json:"currency,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Domain      *string `json:"domain,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless  *string `json:"headless,omitempty"`
	Markdown  *bool   `json:"markdown,omitempty"`
	Merchant  *string `json:"merchant,omitempty"`
	PageFrom  *int    `json:"page_from,omitempty"`
	Parse     *bool   `json:"parse,omitempty"`
	Query     *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	SortBy    *string `json:"sort_by,omitempty"`
	XHR       *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonSearchParams) GetTarget() string { return string(p.Target) }

// NewAmazonSearchParams creates a new AmazonSearchParams with the target pre-set.
func NewAmazonSearchParams() *AmazonSearchParams {
	return &AmazonSearchParams{Target: TargetAmazonSearch}
}

// AmazonSellersParams contains parameters for the amazon_sellers target.
type AmazonSellersParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Domain      *string `json:"domain,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Locale   *string `json:"locale,omitempty"`
	Markdown *bool   `json:"markdown,omitempty"`
	Parse    *bool   `json:"parse,omitempty"`
	Query    *string `json:"query,omitempty"`
	XHR      *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonSellersParams) GetTarget() string { return string(p.Target) }

// NewAmazonSellersParams creates a new AmazonSellersParams with the target pre-set.
func NewAmazonSellersParams() *AmazonSellersParams {
	return &AmazonSellersParams{Target: TargetAmazonSellers}
}

// AppleAppStoreParams contains parameters for the apple_app_store target.
type AppleAppStoreParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool   `json:"markdown,omitempty"`
	URL      *string `json:"url,omitempty"`
	XHR      *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AppleAppStoreParams) GetTarget() string { return string(p.Target) }

// NewAppleAppStoreParams creates a new AppleAppStoreParams with the target pre-set.
func NewAppleAppStoreParams() *AppleAppStoreParams {
	return &AppleAppStoreParams{Target: TargetAppleAppStore}
}

// AutotraderParams contains parameters for the autotrader target.
type AutotraderParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool   `json:"markdown,omitempty"`
	URL      *string `json:"url,omitempty"`
	XHR      *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AutotraderParams) GetTarget() string { return string(p.Target) }

// NewAutotraderParams creates a new AutotraderParams with the target pre-set.
func NewAutotraderParams() *AutotraderParams {
	return &AutotraderParams{Target: TargetAutotrader}
}

// BbbParams contains parameters for the bbb target.
type BbbParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool   `json:"markdown,omitempty"`
	URL      *string `json:"url,omitempty"`
	XHR      *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *BbbParams) GetTarget() string { return string(p.Target) }

// NewBbbParams creates a new BbbParams with the target pre-set.
func NewBbbParams() *BbbParams {
	return &BbbParams{Target: TargetBbb}
}

// BingParams contains parameters for the bing target.
type BingParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless  *string `json:"headless,omitempty"`
	Locale    *string `json:"locale,omitempty"`
	Markdown  *bool   `json:"markdown,omitempty"`
	PageFrom  *int    `json:"page_from,omitempty"`
	Parse     *bool   `json:"parse,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	URL       *string `json:"url,omitempty"`
	XHR       *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *BingParams) GetTarget() string { return string(p.Target) }

// NewBingParams creates a new BingParams with the target pre-set.
func NewBingParams() *BingParams {
	return &BingParams{Target: TargetBing}
}

// BingSearchParams contains parameters for the bing_search target.
type BingSearchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Domain      *string `json:"domain,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless  *string `json:"headless,omitempty"`
	Locale    *string `json:"locale,omitempty"`
	Markdown  *bool   `json:"markdown,omitempty"`
	PageCount *int    `json:"page_count,omitempty"`
	PageFrom  *int    `json:"page_from,omitempty"`
	Parse     *bool   `json:"parse,omitempty"`
	Query     *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	XHR       *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *BingSearchParams) GetTarget() string { return string(p.Target) }

// NewBingSearchParams creates a new BingSearchParams with the target pre-set.
func NewBingSearchParams() *BingSearchParams {
	return &BingSearchParams{Target: TargetBingSearch}
}

// ChatgptParams contains parameters for the chatgpt target.
type ChatgptParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	Markdown    *bool   `json:"markdown,omitempty"`
	Parse       *bool   `json:"parse,omitempty"`
	Prompt      *string `json:"prompt,omitempty"`
	Search      *bool   `json:"search,omitempty"`
	XHR         *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *ChatgptParams) GetTarget() string { return string(p.Target) }

// NewChatgptParams creates a new ChatgptParams with the target pre-set.
func NewChatgptParams() *ChatgptParams {
	return &ChatgptParams{Target: TargetChatgpt}
}

// GeminiParams contains parameters for the gemini target.
type GeminiParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	Parse       *bool   `json:"parse,omitempty"`
	Prompt      *string `json:"prompt,omitempty"`
	XHR         *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GeminiParams) GetTarget() string { return string(p.Target) }

// NewGeminiParams creates a new GeminiParams with the target pre-set.
func NewGeminiParams() *GeminiParams {
	return &GeminiParams{Target: TargetGemini}
}

// GoogleParams contains parameters for the google target.
type GoogleParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless  *string `json:"headless,omitempty"`
	Locale    *string `json:"locale,omitempty"`
	Markdown  *bool   `json:"markdown,omitempty"`
	PageCount *int    `json:"page_count,omitempty"`
	Parse     *bool   `json:"parse,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	URL       *string `json:"url,omitempty"`
	XHR       *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleParams) GetTarget() string { return string(p.Target) }

// NewGoogleParams creates a new GoogleParams with the target pre-set.
func NewGoogleParams() *GoogleParams {
	return &GoogleParams{Target: TargetGoogle}
}

// GoogleAdsParams contains parameters for the google_ads target.
type GoogleAdsParams struct {
	Target                Target  `json:"target"`
	CallbackURL           *string `json:"callback_url,omitempty"`
	DeviceType            *string `json:"device_type,omitempty"`
	Geo                   *string `json:"geo,omitempty"`
	GoogleNfpr            *bool   `json:"google_nfpr,omitempty"`
	GoogleResultsLanguage *string `json:"google_results_language,omitempty"`
	GoogleTbm             *string `json:"google_tbm,omitempty"`
	GoogleTbs             *string `json:"google_tbs,omitempty"`
	// Headless valid values: html, png
	Headless  *string `json:"headless,omitempty"`
	Locale    *string `json:"locale,omitempty"`
	Markdown  *bool   `json:"markdown,omitempty"`
	PageCount *int    `json:"page_count,omitempty"`
	PageFrom  *int    `json:"page_from,omitempty"`
	Parse     *bool   `json:"parse,omitempty"`
	Query     *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	XHR       *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleAdsParams) GetTarget() string { return string(p.Target) }

// NewGoogleAdsParams creates a new GoogleAdsParams with the target pre-set.
func NewGoogleAdsParams() *GoogleAdsParams {
	return &GoogleAdsParams{Target: TargetGoogleAds}
}

// GoogleAiModeParams contains parameters for the google_ai_mode target.
type GoogleAiModeParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	Markdown    *bool   `json:"markdown,omitempty"`
	Parse       *bool   `json:"parse,omitempty"`
	Query       *string `json:"query,omitempty"`
	SessionID   *string `json:"session_id,omitempty"`
	XHR         *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleAiModeParams) GetTarget() string { return string(p.Target) }

// NewGoogleAiModeParams creates a new GoogleAiModeParams with the target pre-set.
func NewGoogleAiModeParams() *GoogleAiModeParams {
	return &GoogleAiModeParams{Target: TargetGoogleAiMode}
}

// GoogleLensParams contains parameters for the google_lens target.
type GoogleLensParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool   `json:"markdown,omitempty"`
	Parse    *bool   `json:"parse,omitempty"`
	Query    *string `json:"query,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleLensParams) GetTarget() string { return string(p.Target) }

// NewGoogleLensParams creates a new GoogleLensParams with the target pre-set.
func NewGoogleLensParams() *GoogleLensParams {
	return &GoogleLensParams{Target: TargetGoogleLens}
}

// GoogleSearchParams contains parameters for the google_search target.
type GoogleSearchParams struct {
	Target                Target  `json:"target"`
	CallbackURL           *string `json:"callback_url,omitempty"`
	DeviceType            *string `json:"device_type,omitempty"`
	Geo                   *string `json:"geo,omitempty"`
	GoogleNfpr            *bool   `json:"google_nfpr,omitempty"`
	GoogleResultsLanguage *string `json:"google_results_language,omitempty"`
	GoogleSafeSearch      *bool   `json:"google_safe_search,omitempty"`
	GoogleTbm             *string `json:"google_tbm,omitempty"`
	GoogleTbs             *string `json:"google_tbs,omitempty"`
	// Headless valid values: html, png
	Headless  *string `json:"headless,omitempty"`
	Locale    *string `json:"locale,omitempty"`
	Markdown  *bool   `json:"markdown,omitempty"`
	PageCount *int    `json:"page_count,omitempty"`
	PageFrom  *int    `json:"page_from,omitempty"`
	Parse     *bool   `json:"parse,omitempty"`
	Query     *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	XHR       *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleSearchParams) GetTarget() string { return string(p.Target) }

// NewGoogleSearchParams creates a new GoogleSearchParams with the target pre-set.
func NewGoogleSearchParams() *GoogleSearchParams {
	return &GoogleSearchParams{Target: TargetGoogleSearch}
}

// GoogleTravelHotelsParams contains parameters for the google_travel_hotels target.
type GoogleTravelHotelsParams struct {
	Target      Target  `json:"target"`
	Adults      *int    `json:"adults,omitempty"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Children    *int    `json:"children,omitempty"`
	DateRange   *string `json:"date_range,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless  *string `json:"headless,omitempty"`
	Locale    *string `json:"locale,omitempty"`
	Markdown  *bool   `json:"markdown,omitempty"`
	PageFrom  *int    `json:"page_from,omitempty"`
	Query     *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	Stars     *int    `json:"stars,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleTravelHotelsParams) GetTarget() string { return string(p.Target) }

// NewGoogleTravelHotelsParams creates a new GoogleTravelHotelsParams with the target pre-set.
func NewGoogleTravelHotelsParams() *GoogleTravelHotelsParams {
	return &GoogleTravelHotelsParams{Target: TargetGoogleTravelHotels}
}

// MobileParams contains parameters for the mobile target.
type MobileParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool   `json:"markdown,omitempty"`
	URL      *string `json:"url,omitempty"`
	XHR      *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *MobileParams) GetTarget() string { return string(p.Target) }

// NewMobileParams creates a new MobileParams with the target pre-set.
func NewMobileParams() *MobileParams {
	return &MobileParams{Target: TargetMobile}
}

// PerplexityParams contains parameters for the perplexity target.
type PerplexityParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	Markdown    *bool   `json:"markdown,omitempty"`
	Parse       *bool   `json:"parse,omitempty"`
	Prompt      *string `json:"prompt,omitempty"`
	XHR         *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *PerplexityParams) GetTarget() string { return string(p.Target) }

// NewPerplexityParams creates a new PerplexityParams with the target pre-set.
func NewPerplexityParams() *PerplexityParams {
	return &PerplexityParams{Target: TargetPerplexity}
}

// RedditPostParams contains parameters for the reddit_post target.
type RedditPostParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	Locale      *string `json:"locale,omitempty"`
	URL         *string `json:"url,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *RedditPostParams) GetTarget() string { return string(p.Target) }

// NewRedditPostParams creates a new RedditPostParams with the target pre-set.
func NewRedditPostParams() *RedditPostParams {
	return &RedditPostParams{Target: TargetRedditPost}
}

// RedditSubredditParams contains parameters for the reddit_subreddit target.
type RedditSubredditParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	Locale      *string `json:"locale,omitempty"`
	URL         *string `json:"url,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *RedditSubredditParams) GetTarget() string { return string(p.Target) }

// NewRedditSubredditParams creates a new RedditSubredditParams with the target pre-set.
func NewRedditSubredditParams() *RedditSubredditParams {
	return &RedditSubredditParams{Target: TargetRedditSubreddit}
}

// RedditUserParams contains parameters for the reddit_user target.
type RedditUserParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	Locale      *string `json:"locale,omitempty"`
	Sort        *string `json:"sort,omitempty"`
	URL         *string `json:"url,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *RedditUserParams) GetTarget() string { return string(p.Target) }

// NewRedditUserParams creates a new RedditUserParams with the target pre-set.
func NewRedditUserParams() *RedditUserParams {
	return &RedditUserParams{Target: TargetRedditUser}
}

// TargetParams contains parameters for the target target.
type TargetParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeliveryZip *string `json:"delivery_zip,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless      *string `json:"headless,omitempty"`
	TargetStoreID *string `json:"target_store_id,omitempty"`
	URL           *string `json:"url,omitempty"`
	XHR           *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TargetParams) GetTarget() string { return string(p.Target) }

// NewTargetParams creates a new TargetParams with the target pre-set.
func NewTargetParams() *TargetParams {
	return &TargetParams{Target: TargetTarget}
}

// TargetProductParams contains parameters for the target_product target.
type TargetProductParams struct {
	Target       Target  `json:"target"`
	CallbackURL  *string `json:"callback_url,omitempty"`
	DeliveryType *string `json:"delivery_type,omitempty"`
	DeliveryZip  *string `json:"delivery_zip,omitempty"`
	DeviceType   *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless      *string `json:"headless,omitempty"`
	Markdown      *bool   `json:"markdown,omitempty"`
	Parse         *bool   `json:"parse,omitempty"`
	ProductID     *string `json:"product_id,omitempty"`
	TargetStoreID *string `json:"target_store_id,omitempty"`
	XHR           *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TargetProductParams) GetTarget() string { return string(p.Target) }

// NewTargetProductParams creates a new TargetProductParams with the target pre-set.
func NewTargetProductParams() *TargetProductParams {
	return &TargetProductParams{Target: TargetTargetProduct}
}

// TargetSearchParams contains parameters for the target_search target.
type TargetSearchParams struct {
	Target       Target  `json:"target"`
	CallbackURL  *string `json:"callback_url,omitempty"`
	DeliveryType *string `json:"delivery_type,omitempty"`
	DeliveryZip  *string `json:"delivery_zip,omitempty"`
	DeviceType   *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless      *string `json:"headless,omitempty"`
	Markdown      *bool   `json:"markdown,omitempty"`
	Parse         *bool   `json:"parse,omitempty"`
	Query         *string `json:"query,omitempty"`
	TargetStoreID *string `json:"target_store_id,omitempty"`
	XHR           *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TargetSearchParams) GetTarget() string { return string(p.Target) }

// NewTargetSearchParams creates a new TargetSearchParams with the target pre-set.
func NewTargetSearchParams() *TargetSearchParams {
	return &TargetSearchParams{Target: TargetTargetSearch}
}

// TiktokParams contains parameters for the tiktok target.
type TiktokParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	// Headless valid values: html, png
	Headless      *string `json:"headless,omitempty"`
	URL           *string `json:"url,omitempty"`
	UserAgentType *string `json:"user_agent_type,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TiktokParams) GetTarget() string { return string(p.Target) }

// NewTiktokParams creates a new TiktokParams with the target pre-set.
func NewTiktokParams() *TiktokParams {
	return &TiktokParams{Target: TargetTiktok}
}

// TiktokPostParams contains parameters for the tiktok_post target.
type TiktokPostParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	URL         *string `json:"url,omitempty"`
	XHR         *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TiktokPostParams) GetTarget() string { return string(p.Target) }

// NewTiktokPostParams creates a new TiktokPostParams with the target pre-set.
func NewTiktokPostParams() *TiktokPostParams {
	return &TiktokPostParams{Target: TargetTiktokPost}
}

// TiktokShopProductParams contains parameters for the tiktok_shop_product target.
type TiktokShopProductParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Country     *string `json:"country,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless  *string `json:"headless,omitempty"`
	Markdown  *bool   `json:"markdown,omitempty"`
	ProductID *string `json:"product_id,omitempty"`
	XHR       *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TiktokShopProductParams) GetTarget() string { return string(p.Target) }

// NewTiktokShopProductParams creates a new TiktokShopProductParams with the target pre-set.
func NewTiktokShopProductParams() *TiktokShopProductParams {
	return &TiktokShopProductParams{Target: TargetTiktokShopProduct}
}

// TiktokShopSearchParams contains parameters for the tiktok_shop_search target.
type TiktokShopSearchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Country     *string `json:"country,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool   `json:"markdown,omitempty"`
	Query    *string `json:"query,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TiktokShopSearchParams) GetTarget() string { return string(p.Target) }

// NewTiktokShopSearchParams creates a new TiktokShopSearchParams with the target pre-set.
func NewTiktokShopSearchParams() *TiktokShopSearchParams {
	return &TiktokShopSearchParams{Target: TargetTiktokShopSearch}
}

// UniversalParams contains parameters for the universal target.
type UniversalParams struct {
	Target       Target                 `json:"target"`
	CallbackURL  *string                `json:"callback_url,omitempty"`
	Cookies      map[string]interface{} `json:"cookies,omitempty"`
	DeviceType   *string                `json:"device_type,omitempty"`
	ForceCookies *bool                  `json:"force_cookies,omitempty"`
	ForceHeaders *bool                  `json:"force_headers,omitempty"`
	Geo          *string                `json:"geo,omitempty"`
	Headers      map[string]interface{} `json:"headers,omitempty"`
	// Headless valid values: html, png
	Headless   *string `json:"headless,omitempty"`
	HTTPMethod *string `json:"http_method,omitempty"`
	Locale     *string `json:"locale,omitempty"`
	Markdown   *bool   `json:"markdown,omitempty"`
	Payload    *string `json:"payload,omitempty"`
	// ProxyPool valid values: standard, premium
	ProxyPool             *string   `json:"proxy_pool,omitempty"`
	SessionID             *string   `json:"session_id,omitempty"`
	SuccessfulStatusCodes []float64 `json:"successful_status_codes,omitempty"`
	URL                   *string   `json:"url,omitempty"`
	XHR                   *bool     `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *UniversalParams) GetTarget() string { return string(p.Target) }

// NewUniversalParams creates a new UniversalParams with the target pre-set.
func NewUniversalParams() *UniversalParams {
	return &UniversalParams{Target: TargetUniversal}
}

// WalmartParams contains parameters for the walmart target.
type WalmartParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Locale   *string `json:"locale,omitempty"`
	Markdown *bool   `json:"markdown,omitempty"`
	StoreID  *string `json:"store_id,omitempty"`
	URL      *string `json:"url,omitempty"`
	XHR      *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *WalmartParams) GetTarget() string { return string(p.Target) }

// NewWalmartParams creates a new WalmartParams with the target pre-set.
func NewWalmartParams() *WalmartParams {
	return &WalmartParams{Target: TargetWalmart}
}

// WalmartProductParams contains parameters for the walmart_product target.
type WalmartProductParams struct {
	Target          Target  `json:"target"`
	CallbackURL     *string `json:"callback_url,omitempty"`
	DeliveryZip     *string `json:"delivery_zip,omitempty"`
	FulfillmentType *string `json:"fulfillment_type,omitempty"`
	// Headless valid values: html, png
	Headless       *string `json:"headless,omitempty"`
	Markdown       *bool   `json:"markdown,omitempty"`
	Parse          *bool   `json:"parse,omitempty"`
	ProductID      *string `json:"product_id,omitempty"`
	WalmartStoreID *string `json:"walmart_store_id,omitempty"`
	XHR            *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *WalmartProductParams) GetTarget() string { return string(p.Target) }

// NewWalmartProductParams creates a new WalmartProductParams with the target pre-set.
func NewWalmartProductParams() *WalmartProductParams {
	return &WalmartProductParams{Target: TargetWalmartProduct}
}

// WalmartSearchParams contains parameters for the walmart_search target.
type WalmartSearchParams struct {
	Target          Target  `json:"target"`
	CallbackURL     *string `json:"callback_url,omitempty"`
	DeliveryZip     *string `json:"delivery_zip,omitempty"`
	FulfillmentType *string `json:"fulfillment_type,omitempty"`
	// Headless valid values: html, png
	Headless       *string `json:"headless,omitempty"`
	Markdown       *bool   `json:"markdown,omitempty"`
	Parse          *bool   `json:"parse,omitempty"`
	Query          *string `json:"query,omitempty"`
	WalmartStoreID *string `json:"walmart_store_id,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *WalmartSearchParams) GetTarget() string { return string(p.Target) }

// NewWalmartSearchParams creates a new WalmartSearchParams with the target pre-set.
func NewWalmartSearchParams() *WalmartSearchParams {
	return &WalmartSearchParams{Target: TargetWalmartSearch}
}

// YoutubeChannelParams contains parameters for the youtube_channel target.
type YoutubeChannelParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Limit       *int    `json:"limit,omitempty"`
	Markdown    *bool   `json:"markdown,omitempty"`
	Parse       *bool   `json:"parse,omitempty"`
	Query       *string `json:"query,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeChannelParams) GetTarget() string { return string(p.Target) }

// NewYoutubeChannelParams creates a new YoutubeChannelParams with the target pre-set.
func NewYoutubeChannelParams() *YoutubeChannelParams {
	return &YoutubeChannelParams{Target: TargetYoutubeChannel}
}

// YoutubeMetadataParams contains parameters for the youtube_metadata target.
type YoutubeMetadataParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Query       *string `json:"query,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeMetadataParams) GetTarget() string { return string(p.Target) }

// NewYoutubeMetadataParams creates a new YoutubeMetadataParams with the target pre-set.
func NewYoutubeMetadataParams() *YoutubeMetadataParams {
	return &YoutubeMetadataParams{Target: TargetYoutubeMetadata}
}

// YoutubeSearchParams contains parameters for the youtube_search target.
type YoutubeSearchParams struct {
	Target          Target  `json:"target"`
	F360            *bool   `json:"360,omitempty"`
	F3d             *bool   `json:"3d,omitempty"`
	F4k             *bool   `json:"4k,omitempty"`
	CallbackURL     *string `json:"callback_url,omitempty"`
	CreativeCommons *bool   `json:"creative_commons,omitempty"`
	Duration        *string `json:"duration,omitempty"`
	Hd              *bool   `json:"hd,omitempty"`
	Hdr             *bool   `json:"hdr,omitempty"`
	Live            *bool   `json:"live,omitempty"`
	Location        *bool   `json:"location,omitempty"`
	Purchased       *bool   `json:"purchased,omitempty"`
	Query           *string `json:"query,omitempty"`
	Subtitles       *bool   `json:"subtitles,omitempty"`
	Type            *string `json:"type,omitempty"`
	UploadDate      *string `json:"upload_date,omitempty"`
	VideoSortBy     *string `json:"video_sort_by,omitempty"`
	Vr180           *bool   `json:"vr180,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeSearchParams) GetTarget() string { return string(p.Target) }

// NewYoutubeSearchParams creates a new YoutubeSearchParams with the target pre-set.
func NewYoutubeSearchParams() *YoutubeSearchParams {
	return &YoutubeSearchParams{Target: TargetYoutubeSearch}
}

// YoutubeSubtitlesParams contains parameters for the youtube_subtitles target.
type YoutubeSubtitlesParams struct {
	Target         Target  `json:"target"`
	CallbackURL    *string `json:"callback_url,omitempty"`
	LanguageCode   *string `json:"language_code,omitempty"`
	Query          *string `json:"query,omitempty"`
	SubtitleOrigin *string `json:"subtitle_origin,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeSubtitlesParams) GetTarget() string { return string(p.Target) }

// NewYoutubeSubtitlesParams creates a new YoutubeSubtitlesParams with the target pre-set.
func NewYoutubeSubtitlesParams() *YoutubeSubtitlesParams {
	return &YoutubeSubtitlesParams{Target: TargetYoutubeSubtitles}
}

// AirbnbBatchParams contains parameters for the airbnb target (batch mode).
type AirbnbBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string  `json:"headless,omitempty"`
	Markdown *bool    `json:"markdown,omitempty"`
	URL      []string `json:"url,omitempty"`
	XHR      *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AirbnbBatchParams) GetTarget() string { return string(p.Target) }

// NewAirbnbBatchParams creates a new AirbnbBatchParams with the target pre-set.
func NewAirbnbBatchParams() *AirbnbBatchParams {
	return &AirbnbBatchParams{Target: TargetAirbnb}
}

// AmazonBatchParams contains parameters for the amazon target (batch mode).
type AmazonBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless  *string  `json:"headless,omitempty"`
	Markdown  *bool    `json:"markdown,omitempty"`
	Parse     *bool    `json:"parse,omitempty"`
	SessionID *string  `json:"session_id,omitempty"`
	URL       []string `json:"url,omitempty"`
	XHR       *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonBatchParams) GetTarget() string { return string(p.Target) }

// NewAmazonBatchParams creates a new AmazonBatchParams with the target pre-set.
func NewAmazonBatchParams() *AmazonBatchParams {
	return &AmazonBatchParams{Target: TargetAmazon}
}

// AmazonBestsellersBatchParams contains parameters for the amazon_bestsellers target (batch mode).
type AmazonBestsellersBatchParams struct {
	Target      Target   `json:"target"`
	CallbackURL *string  `json:"callback_url,omitempty"`
	Category    *string  `json:"category,omitempty"`
	Currency    *string  `json:"currency,omitempty"`
	DeviceType  *string  `json:"device_type,omitempty"`
	Domain      *string  `json:"domain,omitempty"`
	Geo         *string  `json:"geo,omitempty"`
	Markdown    *bool    `json:"markdown,omitempty"`
	PageFrom    *int     `json:"page_from,omitempty"`
	Parse       *bool    `json:"parse,omitempty"`
	Query       []string `json:"query,omitempty"`
	SessionID   *string  `json:"session_id,omitempty"`
	XHR         *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonBestsellersBatchParams) GetTarget() string { return string(p.Target) }

// NewAmazonBestsellersBatchParams creates a new AmazonBestsellersBatchParams with the target pre-set.
func NewAmazonBestsellersBatchParams() *AmazonBestsellersBatchParams {
	return &AmazonBestsellersBatchParams{Target: TargetAmazonBestsellers}
}

// AmazonPricingBatchParams contains parameters for the amazon_pricing target (batch mode).
type AmazonPricingBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Currency    *string `json:"currency,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Domain      *string `json:"domain,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless  *string  `json:"headless,omitempty"`
	Markdown  *bool    `json:"markdown,omitempty"`
	PageFrom  *int     `json:"page_from,omitempty"`
	Parse     *bool    `json:"parse,omitempty"`
	Query     []string `json:"query,omitempty"`
	SessionID *string  `json:"session_id,omitempty"`
	XHR       *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonPricingBatchParams) GetTarget() string { return string(p.Target) }

// NewAmazonPricingBatchParams creates a new AmazonPricingBatchParams with the target pre-set.
func NewAmazonPricingBatchParams() *AmazonPricingBatchParams {
	return &AmazonPricingBatchParams{Target: TargetAmazonPricing}
}

// AmazonProductBatchParams contains parameters for the amazon_product target (batch mode).
type AmazonProductBatchParams struct {
	Target            Target  `json:"target"`
	AutoselectVariant *bool   `json:"autoselect_variant,omitempty"`
	CallbackURL       *string `json:"callback_url,omitempty"`
	Currency          *string `json:"currency,omitempty"`
	DeviceType        *string `json:"device_type,omitempty"`
	Domain            *string `json:"domain,omitempty"`
	Geo               *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless  *string  `json:"headless,omitempty"`
	Markdown  *bool    `json:"markdown,omitempty"`
	Parse     *bool    `json:"parse,omitempty"`
	Query     []string `json:"query,omitempty"`
	SessionID *string  `json:"session_id,omitempty"`
	XHR       *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonProductBatchParams) GetTarget() string { return string(p.Target) }

// NewAmazonProductBatchParams creates a new AmazonProductBatchParams with the target pre-set.
func NewAmazonProductBatchParams() *AmazonProductBatchParams {
	return &AmazonProductBatchParams{Target: TargetAmazonProduct}
}

// AmazonSearchBatchParams contains parameters for the amazon_search target (batch mode).
type AmazonSearchBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Category    *string `json:"category,omitempty"`
	Currency    *string `json:"currency,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Domain      *string `json:"domain,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless  *string  `json:"headless,omitempty"`
	Markdown  *bool    `json:"markdown,omitempty"`
	Merchant  *string  `json:"merchant,omitempty"`
	PageFrom  *int     `json:"page_from,omitempty"`
	Parse     *bool    `json:"parse,omitempty"`
	Query     []string `json:"query,omitempty"`
	SessionID *string  `json:"session_id,omitempty"`
	SortBy    *string  `json:"sort_by,omitempty"`
	XHR       *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonSearchBatchParams) GetTarget() string { return string(p.Target) }

// NewAmazonSearchBatchParams creates a new AmazonSearchBatchParams with the target pre-set.
func NewAmazonSearchBatchParams() *AmazonSearchBatchParams {
	return &AmazonSearchBatchParams{Target: TargetAmazonSearch}
}

// AmazonSellersBatchParams contains parameters for the amazon_sellers target (batch mode).
type AmazonSellersBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Domain      *string `json:"domain,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string  `json:"headless,omitempty"`
	Locale   *string  `json:"locale,omitempty"`
	Markdown *bool    `json:"markdown,omitempty"`
	Parse    *bool    `json:"parse,omitempty"`
	Query    []string `json:"query,omitempty"`
	XHR      *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonSellersBatchParams) GetTarget() string { return string(p.Target) }

// NewAmazonSellersBatchParams creates a new AmazonSellersBatchParams with the target pre-set.
func NewAmazonSellersBatchParams() *AmazonSellersBatchParams {
	return &AmazonSellersBatchParams{Target: TargetAmazonSellers}
}

// AppleAppStoreBatchParams contains parameters for the apple_app_store target (batch mode).
type AppleAppStoreBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string  `json:"headless,omitempty"`
	Markdown *bool    `json:"markdown,omitempty"`
	URL      []string `json:"url,omitempty"`
	XHR      *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AppleAppStoreBatchParams) GetTarget() string { return string(p.Target) }

// NewAppleAppStoreBatchParams creates a new AppleAppStoreBatchParams with the target pre-set.
func NewAppleAppStoreBatchParams() *AppleAppStoreBatchParams {
	return &AppleAppStoreBatchParams{Target: TargetAppleAppStore}
}

// AutotraderBatchParams contains parameters for the autotrader target (batch mode).
type AutotraderBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string  `json:"headless,omitempty"`
	Markdown *bool    `json:"markdown,omitempty"`
	URL      []string `json:"url,omitempty"`
	XHR      *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AutotraderBatchParams) GetTarget() string { return string(p.Target) }

// NewAutotraderBatchParams creates a new AutotraderBatchParams with the target pre-set.
func NewAutotraderBatchParams() *AutotraderBatchParams {
	return &AutotraderBatchParams{Target: TargetAutotrader}
}

// BbbBatchParams contains parameters for the bbb target (batch mode).
type BbbBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string  `json:"headless,omitempty"`
	Markdown *bool    `json:"markdown,omitempty"`
	URL      []string `json:"url,omitempty"`
	XHR      *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *BbbBatchParams) GetTarget() string { return string(p.Target) }

// NewBbbBatchParams creates a new BbbBatchParams with the target pre-set.
func NewBbbBatchParams() *BbbBatchParams {
	return &BbbBatchParams{Target: TargetBbb}
}

// BingBatchParams contains parameters for the bing target (batch mode).
type BingBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless  *string  `json:"headless,omitempty"`
	Locale    *string  `json:"locale,omitempty"`
	Markdown  *bool    `json:"markdown,omitempty"`
	PageFrom  *int     `json:"page_from,omitempty"`
	Parse     *bool    `json:"parse,omitempty"`
	SessionID *string  `json:"session_id,omitempty"`
	URL       []string `json:"url,omitempty"`
	XHR       *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *BingBatchParams) GetTarget() string { return string(p.Target) }

// NewBingBatchParams creates a new BingBatchParams with the target pre-set.
func NewBingBatchParams() *BingBatchParams {
	return &BingBatchParams{Target: TargetBing}
}

// BingSearchBatchParams contains parameters for the bing_search target (batch mode).
type BingSearchBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Domain      *string `json:"domain,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless  *string  `json:"headless,omitempty"`
	Locale    *string  `json:"locale,omitempty"`
	Markdown  *bool    `json:"markdown,omitempty"`
	PageCount *int     `json:"page_count,omitempty"`
	PageFrom  *int     `json:"page_from,omitempty"`
	Parse     *bool    `json:"parse,omitempty"`
	Query     []string `json:"query,omitempty"`
	SessionID *string  `json:"session_id,omitempty"`
	XHR       *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *BingSearchBatchParams) GetTarget() string { return string(p.Target) }

// NewBingSearchBatchParams creates a new BingSearchBatchParams with the target pre-set.
func NewBingSearchBatchParams() *BingSearchBatchParams {
	return &BingSearchBatchParams{Target: TargetBingSearch}
}

// ChatgptBatchParams contains parameters for the chatgpt target (batch mode).
type ChatgptBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	Markdown    *bool   `json:"markdown,omitempty"`
	Parse       *bool   `json:"parse,omitempty"`
	Prompt      *string `json:"prompt,omitempty"`
	Search      *bool   `json:"search,omitempty"`
	XHR         *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *ChatgptBatchParams) GetTarget() string { return string(p.Target) }

// NewChatgptBatchParams creates a new ChatgptBatchParams with the target pre-set.
func NewChatgptBatchParams() *ChatgptBatchParams {
	return &ChatgptBatchParams{Target: TargetChatgpt}
}

// GeminiBatchParams contains parameters for the gemini target (batch mode).
type GeminiBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	Parse       *bool   `json:"parse,omitempty"`
	Prompt      *string `json:"prompt,omitempty"`
	XHR         *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GeminiBatchParams) GetTarget() string { return string(p.Target) }

// NewGeminiBatchParams creates a new GeminiBatchParams with the target pre-set.
func NewGeminiBatchParams() *GeminiBatchParams {
	return &GeminiBatchParams{Target: TargetGemini}
}

// GoogleBatchParams contains parameters for the google target (batch mode).
type GoogleBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless  *string  `json:"headless,omitempty"`
	Locale    *string  `json:"locale,omitempty"`
	Markdown  *bool    `json:"markdown,omitempty"`
	PageCount *int     `json:"page_count,omitempty"`
	Parse     *bool    `json:"parse,omitempty"`
	SessionID *string  `json:"session_id,omitempty"`
	URL       []string `json:"url,omitempty"`
	XHR       *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleBatchParams) GetTarget() string { return string(p.Target) }

// NewGoogleBatchParams creates a new GoogleBatchParams with the target pre-set.
func NewGoogleBatchParams() *GoogleBatchParams {
	return &GoogleBatchParams{Target: TargetGoogle}
}

// GoogleAdsBatchParams contains parameters for the google_ads target (batch mode).
type GoogleAdsBatchParams struct {
	Target                Target  `json:"target"`
	CallbackURL           *string `json:"callback_url,omitempty"`
	DeviceType            *string `json:"device_type,omitempty"`
	Geo                   *string `json:"geo,omitempty"`
	GoogleNfpr            *bool   `json:"google_nfpr,omitempty"`
	GoogleResultsLanguage *string `json:"google_results_language,omitempty"`
	GoogleTbm             *string `json:"google_tbm,omitempty"`
	GoogleTbs             *string `json:"google_tbs,omitempty"`
	// Headless valid values: html, png
	Headless  *string  `json:"headless,omitempty"`
	Locale    *string  `json:"locale,omitempty"`
	Markdown  *bool    `json:"markdown,omitempty"`
	PageCount *int     `json:"page_count,omitempty"`
	PageFrom  *int     `json:"page_from,omitempty"`
	Parse     *bool    `json:"parse,omitempty"`
	Query     []string `json:"query,omitempty"`
	SessionID *string  `json:"session_id,omitempty"`
	XHR       *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleAdsBatchParams) GetTarget() string { return string(p.Target) }

// NewGoogleAdsBatchParams creates a new GoogleAdsBatchParams with the target pre-set.
func NewGoogleAdsBatchParams() *GoogleAdsBatchParams {
	return &GoogleAdsBatchParams{Target: TargetGoogleAds}
}

// GoogleAiModeBatchParams contains parameters for the google_ai_mode target (batch mode).
type GoogleAiModeBatchParams struct {
	Target      Target   `json:"target"`
	CallbackURL *string  `json:"callback_url,omitempty"`
	DeviceType  *string  `json:"device_type,omitempty"`
	Geo         *string  `json:"geo,omitempty"`
	Markdown    *bool    `json:"markdown,omitempty"`
	Parse       *bool    `json:"parse,omitempty"`
	Query       []string `json:"query,omitempty"`
	SessionID   *string  `json:"session_id,omitempty"`
	XHR         *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleAiModeBatchParams) GetTarget() string { return string(p.Target) }

// NewGoogleAiModeBatchParams creates a new GoogleAiModeBatchParams with the target pre-set.
func NewGoogleAiModeBatchParams() *GoogleAiModeBatchParams {
	return &GoogleAiModeBatchParams{Target: TargetGoogleAiMode}
}

// GoogleLensBatchParams contains parameters for the google_lens target (batch mode).
type GoogleLensBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless *string  `json:"headless,omitempty"`
	Markdown *bool    `json:"markdown,omitempty"`
	Parse    *bool    `json:"parse,omitempty"`
	Query    []string `json:"query,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleLensBatchParams) GetTarget() string { return string(p.Target) }

// NewGoogleLensBatchParams creates a new GoogleLensBatchParams with the target pre-set.
func NewGoogleLensBatchParams() *GoogleLensBatchParams {
	return &GoogleLensBatchParams{Target: TargetGoogleLens}
}

// GoogleSearchBatchParams contains parameters for the google_search target (batch mode).
type GoogleSearchBatchParams struct {
	Target                Target  `json:"target"`
	CallbackURL           *string `json:"callback_url,omitempty"`
	DeviceType            *string `json:"device_type,omitempty"`
	Geo                   *string `json:"geo,omitempty"`
	GoogleNfpr            *bool   `json:"google_nfpr,omitempty"`
	GoogleResultsLanguage *string `json:"google_results_language,omitempty"`
	GoogleSafeSearch      *bool   `json:"google_safe_search,omitempty"`
	GoogleTbm             *string `json:"google_tbm,omitempty"`
	GoogleTbs             *string `json:"google_tbs,omitempty"`
	// Headless valid values: html, png
	Headless  *string  `json:"headless,omitempty"`
	Locale    *string  `json:"locale,omitempty"`
	Markdown  *bool    `json:"markdown,omitempty"`
	PageCount *int     `json:"page_count,omitempty"`
	PageFrom  *int     `json:"page_from,omitempty"`
	Parse     *bool    `json:"parse,omitempty"`
	Query     []string `json:"query,omitempty"`
	SessionID *string  `json:"session_id,omitempty"`
	XHR       *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleSearchBatchParams) GetTarget() string { return string(p.Target) }

// NewGoogleSearchBatchParams creates a new GoogleSearchBatchParams with the target pre-set.
func NewGoogleSearchBatchParams() *GoogleSearchBatchParams {
	return &GoogleSearchBatchParams{Target: TargetGoogleSearch}
}

// GoogleTravelHotelsBatchParams contains parameters for the google_travel_hotels target (batch mode).
type GoogleTravelHotelsBatchParams struct {
	Target      Target  `json:"target"`
	Adults      *int    `json:"adults,omitempty"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Children    *int    `json:"children,omitempty"`
	DateRange   *string `json:"date_range,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless  *string  `json:"headless,omitempty"`
	Locale    *string  `json:"locale,omitempty"`
	Markdown  *bool    `json:"markdown,omitempty"`
	PageFrom  *int     `json:"page_from,omitempty"`
	Query     []string `json:"query,omitempty"`
	SessionID *string  `json:"session_id,omitempty"`
	Stars     *int     `json:"stars,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleTravelHotelsBatchParams) GetTarget() string { return string(p.Target) }

// NewGoogleTravelHotelsBatchParams creates a new GoogleTravelHotelsBatchParams with the target pre-set.
func NewGoogleTravelHotelsBatchParams() *GoogleTravelHotelsBatchParams {
	return &GoogleTravelHotelsBatchParams{Target: TargetGoogleTravelHotels}
}

// MobileBatchParams contains parameters for the mobile target (batch mode).
type MobileBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string  `json:"headless,omitempty"`
	Markdown *bool    `json:"markdown,omitempty"`
	URL      []string `json:"url,omitempty"`
	XHR      *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *MobileBatchParams) GetTarget() string { return string(p.Target) }

// NewMobileBatchParams creates a new MobileBatchParams with the target pre-set.
func NewMobileBatchParams() *MobileBatchParams {
	return &MobileBatchParams{Target: TargetMobile}
}

// PerplexityBatchParams contains parameters for the perplexity target (batch mode).
type PerplexityBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	Markdown    *bool   `json:"markdown,omitempty"`
	Parse       *bool   `json:"parse,omitempty"`
	Prompt      *string `json:"prompt,omitempty"`
	XHR         *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *PerplexityBatchParams) GetTarget() string { return string(p.Target) }

// NewPerplexityBatchParams creates a new PerplexityBatchParams with the target pre-set.
func NewPerplexityBatchParams() *PerplexityBatchParams {
	return &PerplexityBatchParams{Target: TargetPerplexity}
}

// RedditPostBatchParams contains parameters for the reddit_post target (batch mode).
type RedditPostBatchParams struct {
	Target      Target   `json:"target"`
	CallbackURL *string  `json:"callback_url,omitempty"`
	Geo         *string  `json:"geo,omitempty"`
	Locale      *string  `json:"locale,omitempty"`
	URL         []string `json:"url,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *RedditPostBatchParams) GetTarget() string { return string(p.Target) }

// NewRedditPostBatchParams creates a new RedditPostBatchParams with the target pre-set.
func NewRedditPostBatchParams() *RedditPostBatchParams {
	return &RedditPostBatchParams{Target: TargetRedditPost}
}

// RedditSubredditBatchParams contains parameters for the reddit_subreddit target (batch mode).
type RedditSubredditBatchParams struct {
	Target      Target   `json:"target"`
	CallbackURL *string  `json:"callback_url,omitempty"`
	Geo         *string  `json:"geo,omitempty"`
	Locale      *string  `json:"locale,omitempty"`
	URL         []string `json:"url,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *RedditSubredditBatchParams) GetTarget() string { return string(p.Target) }

// NewRedditSubredditBatchParams creates a new RedditSubredditBatchParams with the target pre-set.
func NewRedditSubredditBatchParams() *RedditSubredditBatchParams {
	return &RedditSubredditBatchParams{Target: TargetRedditSubreddit}
}

// RedditUserBatchParams contains parameters for the reddit_user target (batch mode).
type RedditUserBatchParams struct {
	Target      Target   `json:"target"`
	CallbackURL *string  `json:"callback_url,omitempty"`
	Geo         *string  `json:"geo,omitempty"`
	Locale      *string  `json:"locale,omitempty"`
	Sort        *string  `json:"sort,omitempty"`
	URL         []string `json:"url,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *RedditUserBatchParams) GetTarget() string { return string(p.Target) }

// NewRedditUserBatchParams creates a new RedditUserBatchParams with the target pre-set.
func NewRedditUserBatchParams() *RedditUserBatchParams {
	return &RedditUserBatchParams{Target: TargetRedditUser}
}

// TargetBatchParams contains parameters for the target target (batch mode).
type TargetBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeliveryZip *string `json:"delivery_zip,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless      *string  `json:"headless,omitempty"`
	TargetStoreID *string  `json:"target_store_id,omitempty"`
	URL           []string `json:"url,omitempty"`
	XHR           *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TargetBatchParams) GetTarget() string { return string(p.Target) }

// NewTargetBatchParams creates a new TargetBatchParams with the target pre-set.
func NewTargetBatchParams() *TargetBatchParams {
	return &TargetBatchParams{Target: TargetTarget}
}

// TargetProductBatchParams contains parameters for the target_product target (batch mode).
type TargetProductBatchParams struct {
	Target       Target  `json:"target"`
	CallbackURL  *string `json:"callback_url,omitempty"`
	DeliveryType *string `json:"delivery_type,omitempty"`
	DeliveryZip  *string `json:"delivery_zip,omitempty"`
	DeviceType   *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless      *string `json:"headless,omitempty"`
	Markdown      *bool   `json:"markdown,omitempty"`
	Parse         *bool   `json:"parse,omitempty"`
	ProductID     *string `json:"product_id,omitempty"`
	TargetStoreID *string `json:"target_store_id,omitempty"`
	XHR           *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TargetProductBatchParams) GetTarget() string { return string(p.Target) }

// NewTargetProductBatchParams creates a new TargetProductBatchParams with the target pre-set.
func NewTargetProductBatchParams() *TargetProductBatchParams {
	return &TargetProductBatchParams{Target: TargetTargetProduct}
}

// TargetSearchBatchParams contains parameters for the target_search target (batch mode).
type TargetSearchBatchParams struct {
	Target       Target  `json:"target"`
	CallbackURL  *string `json:"callback_url,omitempty"`
	DeliveryType *string `json:"delivery_type,omitempty"`
	DeliveryZip  *string `json:"delivery_zip,omitempty"`
	DeviceType   *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless      *string  `json:"headless,omitempty"`
	Markdown      *bool    `json:"markdown,omitempty"`
	Parse         *bool    `json:"parse,omitempty"`
	Query         []string `json:"query,omitempty"`
	TargetStoreID *string  `json:"target_store_id,omitempty"`
	XHR           *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TargetSearchBatchParams) GetTarget() string { return string(p.Target) }

// NewTargetSearchBatchParams creates a new TargetSearchBatchParams with the target pre-set.
func NewTargetSearchBatchParams() *TargetSearchBatchParams {
	return &TargetSearchBatchParams{Target: TargetTargetSearch}
}

// TiktokBatchParams contains parameters for the tiktok target (batch mode).
type TiktokBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	// Headless valid values: html, png
	Headless      *string  `json:"headless,omitempty"`
	URL           []string `json:"url,omitempty"`
	UserAgentType *string  `json:"user_agent_type,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TiktokBatchParams) GetTarget() string { return string(p.Target) }

// NewTiktokBatchParams creates a new TiktokBatchParams with the target pre-set.
func NewTiktokBatchParams() *TiktokBatchParams {
	return &TiktokBatchParams{Target: TargetTiktok}
}

// TiktokPostBatchParams contains parameters for the tiktok_post target (batch mode).
type TiktokPostBatchParams struct {
	Target      Target   `json:"target"`
	CallbackURL *string  `json:"callback_url,omitempty"`
	URL         []string `json:"url,omitempty"`
	XHR         *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TiktokPostBatchParams) GetTarget() string { return string(p.Target) }

// NewTiktokPostBatchParams creates a new TiktokPostBatchParams with the target pre-set.
func NewTiktokPostBatchParams() *TiktokPostBatchParams {
	return &TiktokPostBatchParams{Target: TargetTiktokPost}
}

// TiktokShopProductBatchParams contains parameters for the tiktok_shop_product target (batch mode).
type TiktokShopProductBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Country     *string `json:"country,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless  *string `json:"headless,omitempty"`
	Markdown  *bool   `json:"markdown,omitempty"`
	ProductID *string `json:"product_id,omitempty"`
	XHR       *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TiktokShopProductBatchParams) GetTarget() string { return string(p.Target) }

// NewTiktokShopProductBatchParams creates a new TiktokShopProductBatchParams with the target pre-set.
func NewTiktokShopProductBatchParams() *TiktokShopProductBatchParams {
	return &TiktokShopProductBatchParams{Target: TargetTiktokShopProduct}
}

// TiktokShopSearchBatchParams contains parameters for the tiktok_shop_search target (batch mode).
type TiktokShopSearchBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Country     *string `json:"country,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless *string  `json:"headless,omitempty"`
	Markdown *bool    `json:"markdown,omitempty"`
	Query    []string `json:"query,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TiktokShopSearchBatchParams) GetTarget() string { return string(p.Target) }

// NewTiktokShopSearchBatchParams creates a new TiktokShopSearchBatchParams with the target pre-set.
func NewTiktokShopSearchBatchParams() *TiktokShopSearchBatchParams {
	return &TiktokShopSearchBatchParams{Target: TargetTiktokShopSearch}
}

// UniversalBatchParams contains parameters for the universal target (batch mode).
type UniversalBatchParams struct {
	Target       Target                 `json:"target"`
	CallbackURL  *string                `json:"callback_url,omitempty"`
	Cookies      map[string]interface{} `json:"cookies,omitempty"`
	DeviceType   *string                `json:"device_type,omitempty"`
	ForceCookies *bool                  `json:"force_cookies,omitempty"`
	ForceHeaders *bool                  `json:"force_headers,omitempty"`
	Geo          *string                `json:"geo,omitempty"`
	Headers      map[string]interface{} `json:"headers,omitempty"`
	// Headless valid values: html, png
	Headless   *string `json:"headless,omitempty"`
	HTTPMethod *string `json:"http_method,omitempty"`
	Locale     *string `json:"locale,omitempty"`
	Markdown   *bool   `json:"markdown,omitempty"`
	Payload    *string `json:"payload,omitempty"`
	// ProxyPool valid values: standard, premium
	ProxyPool             *string   `json:"proxy_pool,omitempty"`
	SessionID             *string   `json:"session_id,omitempty"`
	SuccessfulStatusCodes []float64 `json:"successful_status_codes,omitempty"`
	URL                   []string  `json:"url,omitempty"`
	XHR                   *bool     `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *UniversalBatchParams) GetTarget() string { return string(p.Target) }

// NewUniversalBatchParams creates a new UniversalBatchParams with the target pre-set.
func NewUniversalBatchParams() *UniversalBatchParams {
	return &UniversalBatchParams{Target: TargetUniversal}
}

// WalmartBatchParams contains parameters for the walmart target (batch mode).
type WalmartBatchParams struct {
	Target      Target  `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType  *string `json:"device_type,omitempty"`
	Geo         *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string  `json:"headless,omitempty"`
	Locale   *string  `json:"locale,omitempty"`
	Markdown *bool    `json:"markdown,omitempty"`
	StoreID  *string  `json:"store_id,omitempty"`
	URL      []string `json:"url,omitempty"`
	XHR      *bool    `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *WalmartBatchParams) GetTarget() string { return string(p.Target) }

// NewWalmartBatchParams creates a new WalmartBatchParams with the target pre-set.
func NewWalmartBatchParams() *WalmartBatchParams {
	return &WalmartBatchParams{Target: TargetWalmart}
}

// WalmartProductBatchParams contains parameters for the walmart_product target (batch mode).
type WalmartProductBatchParams struct {
	Target          Target  `json:"target"`
	CallbackURL     *string `json:"callback_url,omitempty"`
	DeliveryZip     *string `json:"delivery_zip,omitempty"`
	FulfillmentType *string `json:"fulfillment_type,omitempty"`
	// Headless valid values: html, png
	Headless       *string `json:"headless,omitempty"`
	Markdown       *bool   `json:"markdown,omitempty"`
	Parse          *bool   `json:"parse,omitempty"`
	ProductID      *string `json:"product_id,omitempty"`
	WalmartStoreID *string `json:"walmart_store_id,omitempty"`
	XHR            *bool   `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *WalmartProductBatchParams) GetTarget() string { return string(p.Target) }

// NewWalmartProductBatchParams creates a new WalmartProductBatchParams with the target pre-set.
func NewWalmartProductBatchParams() *WalmartProductBatchParams {
	return &WalmartProductBatchParams{Target: TargetWalmartProduct}
}

// WalmartSearchBatchParams contains parameters for the walmart_search target (batch mode).
type WalmartSearchBatchParams struct {
	Target          Target  `json:"target"`
	CallbackURL     *string `json:"callback_url,omitempty"`
	DeliveryZip     *string `json:"delivery_zip,omitempty"`
	FulfillmentType *string `json:"fulfillment_type,omitempty"`
	// Headless valid values: html, png
	Headless       *string  `json:"headless,omitempty"`
	Markdown       *bool    `json:"markdown,omitempty"`
	Parse          *bool    `json:"parse,omitempty"`
	Query          []string `json:"query,omitempty"`
	WalmartStoreID *string  `json:"walmart_store_id,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *WalmartSearchBatchParams) GetTarget() string { return string(p.Target) }

// NewWalmartSearchBatchParams creates a new WalmartSearchBatchParams with the target pre-set.
func NewWalmartSearchBatchParams() *WalmartSearchBatchParams {
	return &WalmartSearchBatchParams{Target: TargetWalmartSearch}
}

// YoutubeChannelBatchParams contains parameters for the youtube_channel target (batch mode).
type YoutubeChannelBatchParams struct {
	Target      Target   `json:"target"`
	CallbackURL *string  `json:"callback_url,omitempty"`
	Limit       *int     `json:"limit,omitempty"`
	Markdown    *bool    `json:"markdown,omitempty"`
	Parse       *bool    `json:"parse,omitempty"`
	Query       []string `json:"query,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeChannelBatchParams) GetTarget() string { return string(p.Target) }

// NewYoutubeChannelBatchParams creates a new YoutubeChannelBatchParams with the target pre-set.
func NewYoutubeChannelBatchParams() *YoutubeChannelBatchParams {
	return &YoutubeChannelBatchParams{Target: TargetYoutubeChannel}
}

// YoutubeMetadataBatchParams contains parameters for the youtube_metadata target (batch mode).
type YoutubeMetadataBatchParams struct {
	Target      Target   `json:"target"`
	CallbackURL *string  `json:"callback_url,omitempty"`
	Query       []string `json:"query,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeMetadataBatchParams) GetTarget() string { return string(p.Target) }

// NewYoutubeMetadataBatchParams creates a new YoutubeMetadataBatchParams with the target pre-set.
func NewYoutubeMetadataBatchParams() *YoutubeMetadataBatchParams {
	return &YoutubeMetadataBatchParams{Target: TargetYoutubeMetadata}
}

// YoutubeSearchBatchParams contains parameters for the youtube_search target (batch mode).
type YoutubeSearchBatchParams struct {
	Target          Target   `json:"target"`
	F360            *bool    `json:"360,omitempty"`
	F3d             *bool    `json:"3d,omitempty"`
	F4k             *bool    `json:"4k,omitempty"`
	CallbackURL     *string  `json:"callback_url,omitempty"`
	CreativeCommons *bool    `json:"creative_commons,omitempty"`
	Duration        *string  `json:"duration,omitempty"`
	Hd              *bool    `json:"hd,omitempty"`
	Hdr             *bool    `json:"hdr,omitempty"`
	Live            *bool    `json:"live,omitempty"`
	Location        *bool    `json:"location,omitempty"`
	Purchased       *bool    `json:"purchased,omitempty"`
	Query           []string `json:"query,omitempty"`
	Subtitles       *bool    `json:"subtitles,omitempty"`
	Type            *string  `json:"type,omitempty"`
	UploadDate      *string  `json:"upload_date,omitempty"`
	VideoSortBy     *string  `json:"video_sort_by,omitempty"`
	Vr180           *bool    `json:"vr180,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeSearchBatchParams) GetTarget() string { return string(p.Target) }

// NewYoutubeSearchBatchParams creates a new YoutubeSearchBatchParams with the target pre-set.
func NewYoutubeSearchBatchParams() *YoutubeSearchBatchParams {
	return &YoutubeSearchBatchParams{Target: TargetYoutubeSearch}
}

// YoutubeSubtitlesBatchParams contains parameters for the youtube_subtitles target (batch mode).
type YoutubeSubtitlesBatchParams struct {
	Target         Target   `json:"target"`
	CallbackURL    *string  `json:"callback_url,omitempty"`
	LanguageCode   *string  `json:"language_code,omitempty"`
	Query          []string `json:"query,omitempty"`
	SubtitleOrigin *string  `json:"subtitle_origin,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeSubtitlesBatchParams) GetTarget() string { return string(p.Target) }

// NewYoutubeSubtitlesBatchParams creates a new YoutubeSubtitlesBatchParams with the target pre-set.
func NewYoutubeSubtitlesBatchParams() *YoutubeSubtitlesBatchParams {
	return &YoutubeSubtitlesBatchParams{Target: TargetYoutubeSubtitles}
}

// TargetMetaMap contains metadata for all targets.
var TargetMetaMap = map[Target]*TargetInfo{
	TargetAirbnb: {
		Group:          "Travel",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "markdown", "url", "xhr"},
	},
	TargetAmazon: {
		Group:          "Amazon",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "markdown", "parse", "session_id", "url", "xhr"},
	},
	TargetAmazonBestsellers: {
		Group:          "Amazon",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "category", "currency", "device_type", "domain", "geo", "markdown", "page_from", "parse", "query", "session_id", "xhr"},
	},
	TargetAmazonPricing: {
		Group:          "Amazon",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "currency", "device_type", "domain", "geo", "headless", "markdown", "page_from", "parse", "query", "session_id", "xhr"},
	},
	TargetAmazonProduct: {
		Group:          "Amazon",
		ResponseFormat: "json",
		Parameters:     []string{"autoselect_variant", "callback_url", "currency", "device_type", "domain", "geo", "headless", "markdown", "parse", "query", "session_id", "xhr"},
	},
	TargetAmazonSearch: {
		Group:          "Amazon",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "category", "currency", "device_type", "domain", "geo", "headless", "markdown", "merchant", "page_from", "parse", "query", "session_id", "sort_by", "xhr"},
	},
	TargetAmazonSellers: {
		Group:          "Amazon",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "domain", "geo", "headless", "locale", "markdown", "parse", "query", "xhr"},
	},
	TargetAppleAppStore: {
		Group:          "Marketplace",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "markdown", "url", "xhr"},
	},
	TargetAutotrader: {
		Group:          "Marketplace",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "markdown", "url", "xhr"},
	},
	TargetBbb: {
		Group:          "Business Reviews",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "markdown", "url", "xhr"},
	},
	TargetBing: {
		Group:          "Bing",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "locale", "markdown", "page_from", "parse", "session_id", "url", "xhr"},
	},
	TargetBingSearch: {
		Group:          "Bing",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "domain", "geo", "headless", "locale", "markdown", "page_count", "page_from", "parse", "query", "session_id", "xhr"},
	},
	TargetChatgpt: {
		Group:          "AI Tools",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "markdown", "parse", "prompt", "search", "xhr"},
	},
	TargetGemini: {
		Group:          "AI Tools",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "geo", "parse", "prompt", "xhr"},
	},
	TargetGoogle: {
		Group:          "Google",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "headless", "locale", "markdown", "page_count", "parse", "session_id", "url", "xhr"},
	},
	TargetGoogleAds: {
		Group:          "Google",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "google_nfpr", "google_results_language", "google_tbm", "google_tbs", "headless", "locale", "markdown", "page_count", "page_from", "parse", "query", "session_id", "xhr"},
	},
	TargetGoogleAiMode: {
		Group:          "AI Tools",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "markdown", "parse", "query", "session_id", "xhr"},
	},
	TargetGoogleLens: {
		Group:          "Google",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "headless", "markdown", "parse", "query"},
	},
	TargetGoogleSearch: {
		Group:          "Google",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "google_nfpr", "google_results_language", "google_safe_search", "google_tbm", "google_tbs", "headless", "locale", "markdown", "page_count", "page_from", "parse", "query", "session_id", "xhr"},
	},
	TargetGoogleTravelHotels: {
		Group:          "Google",
		ResponseFormat: "html",
		Parameters:     []string{"adults", "callback_url", "children", "date_range", "device_type", "headless", "locale", "markdown", "page_from", "query", "session_id", "stars"},
	},
	TargetMobile: {
		Group:          "Marketplace",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "markdown", "url", "xhr"},
	},
	TargetPerplexity: {
		Group:          "AI Tools",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "markdown", "parse", "prompt", "xhr"},
	},
	TargetRedditPost: {
		Group:          "Reddit",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "geo", "locale", "url"},
	},
	TargetRedditSubreddit: {
		Group:          "Reddit",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "geo", "locale", "url"},
	},
	TargetRedditUser: {
		Group:          "Reddit",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "geo", "locale", "sort", "url"},
	},
	TargetTarget: {
		Group:          "Target",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "delivery_zip", "device_type", "headless", "target_store_id", "url", "xhr"},
	},
	TargetTargetProduct: {
		Group:          "Target",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "delivery_type", "delivery_zip", "device_type", "headless", "markdown", "parse", "product_id", "target_store_id", "xhr"},
	},
	TargetTargetSearch: {
		Group:          "Target",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "delivery_type", "delivery_zip", "device_type", "headless", "markdown", "parse", "query", "target_store_id", "xhr"},
	},
	TargetTiktok: {
		Group:          "TikTok",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "headless", "url", "user_agent_type"},
	},
	TargetTiktokPost: {
		Group:          "TikTok",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "url", "xhr"},
	},
	TargetTiktokShopProduct: {
		Group:          "TikTok",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "country", "device_type", "headless", "markdown", "product_id", "xhr"},
	},
	TargetTiktokShopSearch: {
		Group:          "TikTok",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "country", "device_type", "headless", "markdown", "query"},
	},
	TargetUniversal: {
		Group:          "Universal",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "cookies", "device_type", "force_cookies", "force_headers", "geo", "headers", "headless", "http_method", "locale", "markdown", "payload", "proxy_pool", "session_id", "successful_status_codes", "url", "xhr"},
	},
	TargetWalmart: {
		Group:          "Walmart",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "locale", "markdown", "store_id", "url", "xhr"},
	},
	TargetWalmartProduct: {
		Group:          "Walmart",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "delivery_zip", "fulfillment_type", "headless", "markdown", "parse", "product_id", "walmart_store_id", "xhr"},
	},
	TargetWalmartSearch: {
		Group:          "Walmart",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "delivery_zip", "fulfillment_type", "headless", "markdown", "parse", "query", "walmart_store_id"},
	},
	TargetYoutubeChannel: {
		Group:          "YouTube",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "limit", "markdown", "parse", "query"},
	},
	TargetYoutubeMetadata: {
		Group:          "YouTube",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "query"},
	},
	TargetYoutubeSearch: {
		Group:          "YouTube",
		ResponseFormat: "json",
		Parameters:     []string{"360", "3d", "4k", "callback_url", "creative_commons", "duration", "hd", "hdr", "live", "location", "purchased", "query", "subtitles", "type", "upload_date", "video_sort_by", "vr180"},
	},
	TargetYoutubeSubtitles: {
		Group:          "YouTube",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "language_code", "query", "subtitle_origin"},
	},
}
