// Code generated by cmd/codegen; DO NOT EDIT.

package decodo

// ParameterMeta contains metadata about a scrape parameter.
type ParameterMeta struct {
	Type      string
	MaxLength int
	Minimum   float64
	Maximum   float64
	Enum      []interface{}
	Items     *ItemsMeta
}

// ItemsMeta contains metadata about array item types.
type ItemsMeta struct {
	Type string
}

// ParameterMetaMap contains metadata for all known parameters.
var ParameterMetaMap = map[string]ParameterMeta{
	"callback_url": {Type: "string"},
	"device_type": {Type: "string"},
	"geo": {Type: "string"},
	"headless": {Type: "string", Enum: []interface{}{"html", "png"}},
	"markdown": {Type: "boolean"},
	"url": {Type: "string", MaxLength: 2056},
	"xhr": {Type: "boolean"},
	"parse": {Type: "boolean"},
	"session_id": {Type: "string"},
	"category": {Type: "string"},
	"currency": {Type: "string"},
	"domain": {Type: "string"},
	"page_from": {Type: "number", Minimum: 0, Maximum: 100},
	"query": {Type: "string", MaxLength: 2048},
	"autoselect_variant": {Type: "boolean"},
	"merchant": {Type: "string"},
	"sort_by": {Type: "string"},
	"locale": {Type: "string"},
	"page_count": {Type: "number", Minimum: 1, Maximum: 10},
	"prompt": {Type: "string", MaxLength: 8192},
	"search": {Type: "boolean"},
	"parser_type": {Type: "string"},
	"google_nfpr": {Type: "boolean"},
	"google_results_language": {Type: "string"},
	"google_tbm": {Type: "string"},
	"google_tbs": {Type: "string"},
	"date_range": {Type: "string"},
	"hotel_occupancy": {Type: "string"},
	"google_safe_search": {Type: "boolean"},
	"adults": {Type: "number", Minimum: 1, Maximum: 3},
	"children": {Type: "number", Minimum: 1, Maximum: 3},
	"stars": {Type: "number"},
	"date_end": {Type: "string"},
	"date_start": {Type: "string"},
	"search_type": {Type: "string"},
	"delivery_today_tomorrow": {Type: "boolean"},
	"delivery_zip": {Type: "string"},
	"free_delivery": {Type: "boolean"},
	"lowes_store_id": {Type: "string"},
	"pickup_today": {Type: "boolean"},
	"user_agent_type": {Type: "string"},
	"sort": {Type: "string"},
	"target_store_id": {Type: "string"},
	"delivery_type": {Type: "string"},
	"product_id": {Type: "string"},
	"country": {Type: "string"},
	"cookies": {Type: "object"},
	"force_cookies": {Type: "boolean"},
	"force_headers": {Type: "boolean"},
	"headers": {Type: "object"},
	"http_method": {Type: "string"},
	"payload": {Type: "string"},
	"proxy_pool": {Type: "string", Enum: []interface{}{"standard", "premium"}},
	"successful_status_codes": {Type: "array", Items: &ItemsMeta{Type: "number"}},
	"store_id": {Type: "string"},
	"fulfillment_type": {Type: "string"},
	"walmart_store_id": {Type: "string"},
	"limit": {Type: "number", Minimum: 0, Maximum: 100},
	"360": {Type: "boolean"},
	"3d": {Type: "boolean"},
	"4k": {Type: "boolean"},
	"creative_commons": {Type: "boolean"},
	"duration": {Type: "string"},
	"hd": {Type: "boolean"},
	"hdr": {Type: "boolean"},
	"live": {Type: "boolean"},
	"location": {Type: "boolean"},
	"purchased": {Type: "boolean"},
	"subtitles": {Type: "boolean"},
	"type": {Type: "string"},
	"upload_date": {Type: "string"},
	"video_sort_by": {Type: "string"},
	"vr180": {Type: "boolean"},
	"language_code": {Type: "string"},
	"subtitle_origin": {Type: "string"},
	"transcript_origin": {Type: "string"},
}
