// Code generated by cmd/codegen; DO NOT EDIT.

package decodo

// Target represents the scrape target discriminator.
type Target string

// Target constants for all supported scrape targets.
const (
	TargetAirbnb Target = "airbnb"
	TargetAmazon Target = "amazon"
	TargetAmazonBestsellers Target = "amazon_bestsellers"
	TargetAmazonPricing Target = "amazon_pricing"
	TargetAmazonProduct Target = "amazon_product"
	TargetAmazonSearch Target = "amazon_search"
	TargetAmazonSellers Target = "amazon_sellers"
	TargetAppleAppStore Target = "apple_app_store"
	TargetAutotrader Target = "autotrader"
	TargetBbb Target = "bbb"
	TargetBing Target = "bing"
	TargetBingSearch Target = "bing_search"
	TargetChatgpt Target = "chatgpt"
	TargetEcommerce Target = "ecommerce"
	TargetGemini Target = "gemini"
	TargetGoogle Target = "google"
	TargetGoogleAds Target = "google_ads"
	TargetGoogleAiMode Target = "google_ai_mode"
	TargetGoogleLens Target = "google_lens"
	TargetGoogleMaps Target = "google_maps"
	TargetGoogleSearch Target = "google_search"
	TargetGoogleShoppingProduct Target = "google_shopping_product"
	TargetGoogleShoppingSearch Target = "google_shopping_search"
	TargetGoogleSuggest Target = "google_suggest"
	TargetGoogleTravelHotels Target = "google_travel_hotels"
	TargetGoogleTrendsExplore Target = "google_trends_explore"
	TargetInstagramGraphqlProfile Target = "instagram_graphql_profile"
	TargetLowesSearch Target = "lowes_search"
	TargetMobile Target = "mobile"
	TargetPerplexity Target = "perplexity"
	TargetRedditPost Target = "reddit_post"
	TargetRedditSubreddit Target = "reddit_subreddit"
	TargetRedditUser Target = "reddit_user"
	TargetTarget Target = "target"
	TargetTargetProduct Target = "target_product"
	TargetTargetSearch Target = "target_search"
	TargetTiktok Target = "tiktok"
	TargetTiktokPost Target = "tiktok_post"
	TargetTiktokShopProduct Target = "tiktok_shop_product"
	TargetTiktokShopSearch Target = "tiktok_shop_search"
	TargetUniversal Target = "universal"
	TargetUniversalEcommerce Target = "universal_ecommerce"
	TargetWalmart Target = "walmart"
	TargetWalmartProduct Target = "walmart_product"
	TargetWalmartSearch Target = "walmart_search"
	TargetYoutubeChannel Target = "youtube_channel"
	TargetYoutubeMetadata Target = "youtube_metadata"
	TargetYoutubeSearch Target = "youtube_search"
	TargetYoutubeSearchMax Target = "youtube_search_max"
	TargetYoutubeSubtitles Target = "youtube_subtitles"
	TargetYoutubeTranscript Target = "youtube_transcript"
	TargetYoutubeVideo Target = "youtube_video"
)

// Targets contains all available scrape targets.
var Targets = []Target{
	TargetAirbnb,
	TargetAmazon,
	TargetAmazonBestsellers,
	TargetAmazonPricing,
	TargetAmazonProduct,
	TargetAmazonSearch,
	TargetAmazonSellers,
	TargetAppleAppStore,
	TargetAutotrader,
	TargetBbb,
	TargetBing,
	TargetBingSearch,
	TargetChatgpt,
	TargetEcommerce,
	TargetGemini,
	TargetGoogle,
	TargetGoogleAds,
	TargetGoogleAiMode,
	TargetGoogleLens,
	TargetGoogleMaps,
	TargetGoogleSearch,
	TargetGoogleShoppingProduct,
	TargetGoogleShoppingSearch,
	TargetGoogleSuggest,
	TargetGoogleTravelHotels,
	TargetGoogleTrendsExplore,
	TargetInstagramGraphqlProfile,
	TargetLowesSearch,
	TargetMobile,
	TargetPerplexity,
	TargetRedditPost,
	TargetRedditSubreddit,
	TargetRedditUser,
	TargetTarget,
	TargetTargetProduct,
	TargetTargetSearch,
	TargetTiktok,
	TargetTiktokPost,
	TargetTiktokShopProduct,
	TargetTiktokShopSearch,
	TargetUniversal,
	TargetUniversalEcommerce,
	TargetWalmart,
	TargetWalmartProduct,
	TargetWalmartSearch,
	TargetYoutubeChannel,
	TargetYoutubeMetadata,
	TargetYoutubeSearch,
	TargetYoutubeSearchMax,
	TargetYoutubeSubtitles,
	TargetYoutubeTranscript,
	TargetYoutubeVideo,
}

// AirbnbParams contains parameters for the airbnb target.
type AirbnbParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	URL *string `json:"url,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AirbnbParams) GetTarget() string { return string(p.Target) }

// NewAirbnbParams creates a new AirbnbParams with the target pre-set.
func NewAirbnbParams() *AirbnbParams {
	return &AirbnbParams{Target: TargetAirbnb}
}

// AmazonParams contains parameters for the amazon target.
type AmazonParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	URL *string `json:"url,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonParams) GetTarget() string { return string(p.Target) }

// NewAmazonParams creates a new AmazonParams with the target pre-set.
func NewAmazonParams() *AmazonParams {
	return &AmazonParams{Target: TargetAmazon}
}

// AmazonBestsellersParams contains parameters for the amazon_bestsellers target.
type AmazonBestsellersParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Category *string `json:"category,omitempty"`
	Currency *string `json:"currency,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Domain *string `json:"domain,omitempty"`
	Geo *string `json:"geo,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	PageFrom *float64 `json:"page_from,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonBestsellersParams) GetTarget() string { return string(p.Target) }

// NewAmazonBestsellersParams creates a new AmazonBestsellersParams with the target pre-set.
func NewAmazonBestsellersParams() *AmazonBestsellersParams {
	return &AmazonBestsellersParams{Target: TargetAmazonBestsellers}
}

// AmazonPricingParams contains parameters for the amazon_pricing target.
type AmazonPricingParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Currency *string `json:"currency,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Domain *string `json:"domain,omitempty"`
	Geo *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	PageFrom *float64 `json:"page_from,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonPricingParams) GetTarget() string { return string(p.Target) }

// NewAmazonPricingParams creates a new AmazonPricingParams with the target pre-set.
func NewAmazonPricingParams() *AmazonPricingParams {
	return &AmazonPricingParams{Target: TargetAmazonPricing}
}

// AmazonProductParams contains parameters for the amazon_product target.
type AmazonProductParams struct {
	Target Target `json:"target"`
	AutoselectVariant *bool `json:"autoselect_variant,omitempty"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Currency *string `json:"currency,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Domain *string `json:"domain,omitempty"`
	Geo *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonProductParams) GetTarget() string { return string(p.Target) }

// NewAmazonProductParams creates a new AmazonProductParams with the target pre-set.
func NewAmazonProductParams() *AmazonProductParams {
	return &AmazonProductParams{Target: TargetAmazonProduct}
}

// AmazonSearchParams contains parameters for the amazon_search target.
type AmazonSearchParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Category *string `json:"category,omitempty"`
	Currency *string `json:"currency,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Domain *string `json:"domain,omitempty"`
	Geo *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Merchant *string `json:"merchant,omitempty"`
	PageFrom *float64 `json:"page_from,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	SortBy *string `json:"sort_by,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonSearchParams) GetTarget() string { return string(p.Target) }

// NewAmazonSearchParams creates a new AmazonSearchParams with the target pre-set.
func NewAmazonSearchParams() *AmazonSearchParams {
	return &AmazonSearchParams{Target: TargetAmazonSearch}
}

// AmazonSellersParams contains parameters for the amazon_sellers target.
type AmazonSellersParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Domain *string `json:"domain,omitempty"`
	Geo *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AmazonSellersParams) GetTarget() string { return string(p.Target) }

// NewAmazonSellersParams creates a new AmazonSellersParams with the target pre-set.
func NewAmazonSellersParams() *AmazonSellersParams {
	return &AmazonSellersParams{Target: TargetAmazonSellers}
}

// AppleAppStoreParams contains parameters for the apple_app_store target.
type AppleAppStoreParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	URL *string `json:"url,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AppleAppStoreParams) GetTarget() string { return string(p.Target) }

// NewAppleAppStoreParams creates a new AppleAppStoreParams with the target pre-set.
func NewAppleAppStoreParams() *AppleAppStoreParams {
	return &AppleAppStoreParams{Target: TargetAppleAppStore}
}

// AutotraderParams contains parameters for the autotrader target.
type AutotraderParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	URL *string `json:"url,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *AutotraderParams) GetTarget() string { return string(p.Target) }

// NewAutotraderParams creates a new AutotraderParams with the target pre-set.
func NewAutotraderParams() *AutotraderParams {
	return &AutotraderParams{Target: TargetAutotrader}
}

// BbbParams contains parameters for the bbb target.
type BbbParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	URL *string `json:"url,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *BbbParams) GetTarget() string { return string(p.Target) }

// NewBbbParams creates a new BbbParams with the target pre-set.
func NewBbbParams() *BbbParams {
	return &BbbParams{Target: TargetBbb}
}

// BingParams contains parameters for the bing target.
type BingParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	PageFrom *float64 `json:"page_from,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	URL *string `json:"url,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *BingParams) GetTarget() string { return string(p.Target) }

// NewBingParams creates a new BingParams with the target pre-set.
func NewBingParams() *BingParams {
	return &BingParams{Target: TargetBing}
}

// BingSearchParams contains parameters for the bing_search target.
type BingSearchParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Domain *string `json:"domain,omitempty"`
	Geo *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	PageCount *float64 `json:"page_count,omitempty"`
	PageFrom *float64 `json:"page_from,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *BingSearchParams) GetTarget() string { return string(p.Target) }

// NewBingSearchParams creates a new BingSearchParams with the target pre-set.
func NewBingSearchParams() *BingSearchParams {
	return &BingSearchParams{Target: TargetBingSearch}
}

// ChatgptParams contains parameters for the chatgpt target.
type ChatgptParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Prompt *string `json:"prompt,omitempty"`
	Search *bool `json:"search,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *ChatgptParams) GetTarget() string { return string(p.Target) }

// NewChatgptParams creates a new ChatgptParams with the target pre-set.
func NewChatgptParams() *ChatgptParams {
	return &ChatgptParams{Target: TargetChatgpt}
}

// EcommerceParams contains parameters for the ecommerce target.
type EcommerceParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	ParserType *string `json:"parser_type,omitempty"`
	URL *string `json:"url,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *EcommerceParams) GetTarget() string { return string(p.Target) }

// NewEcommerceParams creates a new EcommerceParams with the target pre-set.
func NewEcommerceParams() *EcommerceParams {
	return &EcommerceParams{Target: TargetEcommerce}
}

// GeminiParams contains parameters for the gemini target.
type GeminiParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Geo *string `json:"geo,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Prompt *string `json:"prompt,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GeminiParams) GetTarget() string { return string(p.Target) }

// NewGeminiParams creates a new GeminiParams with the target pre-set.
func NewGeminiParams() *GeminiParams {
	return &GeminiParams{Target: TargetGemini}
}

// GoogleParams contains parameters for the google target.
type GoogleParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	PageCount *float64 `json:"page_count,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	URL *string `json:"url,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleParams) GetTarget() string { return string(p.Target) }

// NewGoogleParams creates a new GoogleParams with the target pre-set.
func NewGoogleParams() *GoogleParams {
	return &GoogleParams{Target: TargetGoogle}
}

// GoogleAdsParams contains parameters for the google_ads target.
type GoogleAdsParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	GoogleNfpr *bool `json:"google_nfpr,omitempty"`
	GoogleResultsLanguage *string `json:"google_results_language,omitempty"`
	GoogleTbm *string `json:"google_tbm,omitempty"`
	GoogleTbs *string `json:"google_tbs,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	PageCount *float64 `json:"page_count,omitempty"`
	PageFrom *float64 `json:"page_from,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleAdsParams) GetTarget() string { return string(p.Target) }

// NewGoogleAdsParams creates a new GoogleAdsParams with the target pre-set.
func NewGoogleAdsParams() *GoogleAdsParams {
	return &GoogleAdsParams{Target: TargetGoogleAds}
}

// GoogleAiModeParams contains parameters for the google_ai_mode target.
type GoogleAiModeParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleAiModeParams) GetTarget() string { return string(p.Target) }

// NewGoogleAiModeParams creates a new GoogleAiModeParams with the target pre-set.
func NewGoogleAiModeParams() *GoogleAiModeParams {
	return &GoogleAiModeParams{Target: TargetGoogleAiMode}
}

// GoogleLensParams contains parameters for the google_lens target.
type GoogleLensParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleLensParams) GetTarget() string { return string(p.Target) }

// NewGoogleLensParams creates a new GoogleLensParams with the target pre-set.
func NewGoogleLensParams() *GoogleLensParams {
	return &GoogleLensParams{Target: TargetGoogleLens}
}

// GoogleMapsParams contains parameters for the google_maps target.
type GoogleMapsParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DateRange *string `json:"date_range,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	GoogleNfpr *bool `json:"google_nfpr,omitempty"`
	GoogleResultsLanguage *string `json:"google_results_language,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	HotelOccupancy *string `json:"hotel_occupancy,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	PageFrom *float64 `json:"page_from,omitempty"`
	Query *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleMapsParams) GetTarget() string { return string(p.Target) }

// NewGoogleMapsParams creates a new GoogleMapsParams with the target pre-set.
func NewGoogleMapsParams() *GoogleMapsParams {
	return &GoogleMapsParams{Target: TargetGoogleMaps}
}

// GoogleSearchParams contains parameters for the google_search target.
type GoogleSearchParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	GoogleNfpr *bool `json:"google_nfpr,omitempty"`
	GoogleResultsLanguage *string `json:"google_results_language,omitempty"`
	GoogleSafeSearch *bool `json:"google_safe_search,omitempty"`
	GoogleTbm *string `json:"google_tbm,omitempty"`
	GoogleTbs *string `json:"google_tbs,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	PageCount *float64 `json:"page_count,omitempty"`
	PageFrom *float64 `json:"page_from,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleSearchParams) GetTarget() string { return string(p.Target) }

// NewGoogleSearchParams creates a new GoogleSearchParams with the target pre-set.
func NewGoogleSearchParams() *GoogleSearchParams {
	return &GoogleSearchParams{Target: TargetGoogleSearch}
}

// GoogleShoppingProductParams contains parameters for the google_shopping_product target.
type GoogleShoppingProductParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	GoogleResultsLanguage *string `json:"google_results_language,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	PageFrom *float64 `json:"page_from,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleShoppingProductParams) GetTarget() string { return string(p.Target) }

// NewGoogleShoppingProductParams creates a new GoogleShoppingProductParams with the target pre-set.
func NewGoogleShoppingProductParams() *GoogleShoppingProductParams {
	return &GoogleShoppingProductParams{Target: TargetGoogleShoppingProduct}
}

// GoogleShoppingSearchParams contains parameters for the google_shopping_search target.
type GoogleShoppingSearchParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	GoogleResultsLanguage *string `json:"google_results_language,omitempty"`
	GoogleTbs *string `json:"google_tbs,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	PageFrom *float64 `json:"page_from,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleShoppingSearchParams) GetTarget() string { return string(p.Target) }

// NewGoogleShoppingSearchParams creates a new GoogleShoppingSearchParams with the target pre-set.
func NewGoogleShoppingSearchParams() *GoogleShoppingSearchParams {
	return &GoogleShoppingSearchParams{Target: TargetGoogleShoppingSearch}
}

// GoogleSuggestParams contains parameters for the google_suggest target.
type GoogleSuggestParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Query *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleSuggestParams) GetTarget() string { return string(p.Target) }

// NewGoogleSuggestParams creates a new GoogleSuggestParams with the target pre-set.
func NewGoogleSuggestParams() *GoogleSuggestParams {
	return &GoogleSuggestParams{Target: TargetGoogleSuggest}
}

// GoogleTravelHotelsParams contains parameters for the google_travel_hotels target.
type GoogleTravelHotelsParams struct {
	Target Target `json:"target"`
	Adults *float64 `json:"adults,omitempty"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Children *float64 `json:"children,omitempty"`
	DateRange *string `json:"date_range,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	PageFrom *float64 `json:"page_from,omitempty"`
	Query *string `json:"query,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	Stars *float64 `json:"stars,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleTravelHotelsParams) GetTarget() string { return string(p.Target) }

// NewGoogleTravelHotelsParams creates a new GoogleTravelHotelsParams with the target pre-set.
func NewGoogleTravelHotelsParams() *GoogleTravelHotelsParams {
	return &GoogleTravelHotelsParams{Target: TargetGoogleTravelHotels}
}

// GoogleTrendsExploreParams contains parameters for the google_trends_explore target.
type GoogleTrendsExploreParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DateEnd *string `json:"date_end,omitempty"`
	DateStart *string `json:"date_start,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	Query *string `json:"query,omitempty"`
	SearchType *string `json:"search_type,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *GoogleTrendsExploreParams) GetTarget() string { return string(p.Target) }

// NewGoogleTrendsExploreParams creates a new GoogleTrendsExploreParams with the target pre-set.
func NewGoogleTrendsExploreParams() *GoogleTrendsExploreParams {
	return &GoogleTrendsExploreParams{Target: TargetGoogleTrendsExplore}
}

// InstagramGraphqlProfileParams contains parameters for the instagram_graphql_profile target.
type InstagramGraphqlProfileParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Query *string `json:"query,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *InstagramGraphqlProfileParams) GetTarget() string { return string(p.Target) }

// NewInstagramGraphqlProfileParams creates a new InstagramGraphqlProfileParams with the target pre-set.
func NewInstagramGraphqlProfileParams() *InstagramGraphqlProfileParams {
	return &InstagramGraphqlProfileParams{Target: TargetInstagramGraphqlProfile}
}

// LowesSearchParams contains parameters for the lowes_search target.
type LowesSearchParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeliveryTodayTomorrow *bool `json:"delivery_today_tomorrow,omitempty"`
	DeliveryZip *string `json:"delivery_zip,omitempty"`
	FreeDelivery *bool `json:"free_delivery,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	LowesStoreID *string `json:"lowes_store_id,omitempty"`
	PickupToday *bool `json:"pickup_today,omitempty"`
	Query *string `json:"query,omitempty"`
	UserAgentType *string `json:"user_agent_type,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *LowesSearchParams) GetTarget() string { return string(p.Target) }

// NewLowesSearchParams creates a new LowesSearchParams with the target pre-set.
func NewLowesSearchParams() *LowesSearchParams {
	return &LowesSearchParams{Target: TargetLowesSearch}
}

// MobileParams contains parameters for the mobile target.
type MobileParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	URL *string `json:"url,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *MobileParams) GetTarget() string { return string(p.Target) }

// NewMobileParams creates a new MobileParams with the target pre-set.
func NewMobileParams() *MobileParams {
	return &MobileParams{Target: TargetMobile}
}

// PerplexityParams contains parameters for the perplexity target.
type PerplexityParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Prompt *string `json:"prompt,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *PerplexityParams) GetTarget() string { return string(p.Target) }

// NewPerplexityParams creates a new PerplexityParams with the target pre-set.
func NewPerplexityParams() *PerplexityParams {
	return &PerplexityParams{Target: TargetPerplexity}
}

// RedditPostParams contains parameters for the reddit_post target.
type RedditPostParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Geo *string `json:"geo,omitempty"`
	Locale *string `json:"locale,omitempty"`
	URL *string `json:"url,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *RedditPostParams) GetTarget() string { return string(p.Target) }

// NewRedditPostParams creates a new RedditPostParams with the target pre-set.
func NewRedditPostParams() *RedditPostParams {
	return &RedditPostParams{Target: TargetRedditPost}
}

// RedditSubredditParams contains parameters for the reddit_subreddit target.
type RedditSubredditParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Geo *string `json:"geo,omitempty"`
	Locale *string `json:"locale,omitempty"`
	URL *string `json:"url,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *RedditSubredditParams) GetTarget() string { return string(p.Target) }

// NewRedditSubredditParams creates a new RedditSubredditParams with the target pre-set.
func NewRedditSubredditParams() *RedditSubredditParams {
	return &RedditSubredditParams{Target: TargetRedditSubreddit}
}

// RedditUserParams contains parameters for the reddit_user target.
type RedditUserParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Geo *string `json:"geo,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Sort *string `json:"sort,omitempty"`
	URL *string `json:"url,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *RedditUserParams) GetTarget() string { return string(p.Target) }

// NewRedditUserParams creates a new RedditUserParams with the target pre-set.
func NewRedditUserParams() *RedditUserParams {
	return &RedditUserParams{Target: TargetRedditUser}
}

// TargetParams contains parameters for the target target.
type TargetParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeliveryZip *string `json:"delivery_zip,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	TargetStoreID *string `json:"target_store_id,omitempty"`
	URL *string `json:"url,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TargetParams) GetTarget() string { return string(p.Target) }

// NewTargetParams creates a new TargetParams with the target pre-set.
func NewTargetParams() *TargetParams {
	return &TargetParams{Target: TargetTarget}
}

// TargetProductParams contains parameters for the target_product target.
type TargetProductParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeliveryType *string `json:"delivery_type,omitempty"`
	DeliveryZip *string `json:"delivery_zip,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	ProductID *string `json:"product_id,omitempty"`
	TargetStoreID *string `json:"target_store_id,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TargetProductParams) GetTarget() string { return string(p.Target) }

// NewTargetProductParams creates a new TargetProductParams with the target pre-set.
func NewTargetProductParams() *TargetProductParams {
	return &TargetProductParams{Target: TargetTargetProduct}
}

// TargetSearchParams contains parameters for the target_search target.
type TargetSearchParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeliveryType *string `json:"delivery_type,omitempty"`
	DeliveryZip *string `json:"delivery_zip,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
	TargetStoreID *string `json:"target_store_id,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TargetSearchParams) GetTarget() string { return string(p.Target) }

// NewTargetSearchParams creates a new TargetSearchParams with the target pre-set.
func NewTargetSearchParams() *TargetSearchParams {
	return &TargetSearchParams{Target: TargetTargetSearch}
}

// TiktokParams contains parameters for the tiktok target.
type TiktokParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	URL *string `json:"url,omitempty"`
	UserAgentType *string `json:"user_agent_type,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TiktokParams) GetTarget() string { return string(p.Target) }

// NewTiktokParams creates a new TiktokParams with the target pre-set.
func NewTiktokParams() *TiktokParams {
	return &TiktokParams{Target: TargetTiktok}
}

// TiktokPostParams contains parameters for the tiktok_post target.
type TiktokPostParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	URL *string `json:"url,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TiktokPostParams) GetTarget() string { return string(p.Target) }

// NewTiktokPostParams creates a new TiktokPostParams with the target pre-set.
func NewTiktokPostParams() *TiktokPostParams {
	return &TiktokPostParams{Target: TargetTiktokPost}
}

// TiktokShopProductParams contains parameters for the tiktok_shop_product target.
type TiktokShopProductParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Country *string `json:"country,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	ProductID *string `json:"product_id,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TiktokShopProductParams) GetTarget() string { return string(p.Target) }

// NewTiktokShopProductParams creates a new TiktokShopProductParams with the target pre-set.
func NewTiktokShopProductParams() *TiktokShopProductParams {
	return &TiktokShopProductParams{Target: TargetTiktokShopProduct}
}

// TiktokShopSearchParams contains parameters for the tiktok_shop_search target.
type TiktokShopSearchParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Country *string `json:"country,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Query *string `json:"query,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *TiktokShopSearchParams) GetTarget() string { return string(p.Target) }

// NewTiktokShopSearchParams creates a new TiktokShopSearchParams with the target pre-set.
func NewTiktokShopSearchParams() *TiktokShopSearchParams {
	return &TiktokShopSearchParams{Target: TargetTiktokShopSearch}
}

// UniversalParams contains parameters for the universal target.
type UniversalParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Cookies map[string]interface{} `json:"cookies,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	ForceCookies *bool `json:"force_cookies,omitempty"`
	ForceHeaders *bool `json:"force_headers,omitempty"`
	Geo *string `json:"geo,omitempty"`
	Headers map[string]interface{} `json:"headers,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	HTTPMethod *string `json:"http_method,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Payload *string `json:"payload,omitempty"`
	// ProxyPool valid values: standard, premium
	ProxyPool *string `json:"proxy_pool,omitempty"`
	SessionID *string `json:"session_id,omitempty"`
	SuccessfulStatusCodes []float64 `json:"successful_status_codes,omitempty"`
	URL *string `json:"url,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *UniversalParams) GetTarget() string { return string(p.Target) }

// NewUniversalParams creates a new UniversalParams with the target pre-set.
func NewUniversalParams() *UniversalParams {
	return &UniversalParams{Target: TargetUniversal}
}

// UniversalEcommerceParams contains parameters for the universal_ecommerce target.
type UniversalEcommerceParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *UniversalEcommerceParams) GetTarget() string { return string(p.Target) }

// NewUniversalEcommerceParams creates a new UniversalEcommerceParams with the target pre-set.
func NewUniversalEcommerceParams() *UniversalEcommerceParams {
	return &UniversalEcommerceParams{Target: TargetUniversalEcommerce}
}

// WalmartParams contains parameters for the walmart target.
type WalmartParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	Geo *string `json:"geo,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	StoreID *string `json:"store_id,omitempty"`
	URL *string `json:"url,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *WalmartParams) GetTarget() string { return string(p.Target) }

// NewWalmartParams creates a new WalmartParams with the target pre-set.
func NewWalmartParams() *WalmartParams {
	return &WalmartParams{Target: TargetWalmart}
}

// WalmartProductParams contains parameters for the walmart_product target.
type WalmartProductParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeliveryZip *string `json:"delivery_zip,omitempty"`
	FulfillmentType *string `json:"fulfillment_type,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	ProductID *string `json:"product_id,omitempty"`
	WalmartStoreID *string `json:"walmart_store_id,omitempty"`
	XHR *bool `json:"xhr,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *WalmartProductParams) GetTarget() string { return string(p.Target) }

// NewWalmartProductParams creates a new WalmartProductParams with the target pre-set.
func NewWalmartProductParams() *WalmartProductParams {
	return &WalmartProductParams{Target: TargetWalmartProduct}
}

// WalmartSearchParams contains parameters for the walmart_search target.
type WalmartSearchParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	DeliveryZip *string `json:"delivery_zip,omitempty"`
	FulfillmentType *string `json:"fulfillment_type,omitempty"`
	// Headless valid values: html, png
	Headless *string `json:"headless,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
	WalmartStoreID *string `json:"walmart_store_id,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *WalmartSearchParams) GetTarget() string { return string(p.Target) }

// NewWalmartSearchParams creates a new WalmartSearchParams with the target pre-set.
func NewWalmartSearchParams() *WalmartSearchParams {
	return &WalmartSearchParams{Target: TargetWalmartSearch}
}

// YoutubeChannelParams contains parameters for the youtube_channel target.
type YoutubeChannelParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Limit *float64 `json:"limit,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Parse *bool `json:"parse,omitempty"`
	Query *string `json:"query,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeChannelParams) GetTarget() string { return string(p.Target) }

// NewYoutubeChannelParams creates a new YoutubeChannelParams with the target pre-set.
func NewYoutubeChannelParams() *YoutubeChannelParams {
	return &YoutubeChannelParams{Target: TargetYoutubeChannel}
}

// YoutubeMetadataParams contains parameters for the youtube_metadata target.
type YoutubeMetadataParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Query *string `json:"query,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeMetadataParams) GetTarget() string { return string(p.Target) }

// NewYoutubeMetadataParams creates a new YoutubeMetadataParams with the target pre-set.
func NewYoutubeMetadataParams() *YoutubeMetadataParams {
	return &YoutubeMetadataParams{Target: TargetYoutubeMetadata}
}

// YoutubeSearchParams contains parameters for the youtube_search target.
type YoutubeSearchParams struct {
	Target Target `json:"target"`
	F360 *bool `json:"360,omitempty"`
	F3d *bool `json:"3d,omitempty"`
	F4k *bool `json:"4k,omitempty"`
	CallbackURL *string `json:"callback_url,omitempty"`
	CreativeCommons *bool `json:"creative_commons,omitempty"`
	Duration *string `json:"duration,omitempty"`
	Hd *bool `json:"hd,omitempty"`
	Hdr *bool `json:"hdr,omitempty"`
	Live *bool `json:"live,omitempty"`
	Location *bool `json:"location,omitempty"`
	Purchased *bool `json:"purchased,omitempty"`
	Query *string `json:"query,omitempty"`
	Subtitles *bool `json:"subtitles,omitempty"`
	Type *string `json:"type,omitempty"`
	UploadDate *string `json:"upload_date,omitempty"`
	VideoSortBy *string `json:"video_sort_by,omitempty"`
	Vr180 *bool `json:"vr180,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeSearchParams) GetTarget() string { return string(p.Target) }

// NewYoutubeSearchParams creates a new YoutubeSearchParams with the target pre-set.
func NewYoutubeSearchParams() *YoutubeSearchParams {
	return &YoutubeSearchParams{Target: TargetYoutubeSearch}
}

// YoutubeSearchMaxParams contains parameters for the youtube_search_max target.
type YoutubeSearchMaxParams struct {
	Target Target `json:"target"`
	F360 *bool `json:"360,omitempty"`
	F3d *bool `json:"3d,omitempty"`
	F4k *bool `json:"4k,omitempty"`
	CallbackURL *string `json:"callback_url,omitempty"`
	CreativeCommons *bool `json:"creative_commons,omitempty"`
	Duration *string `json:"duration,omitempty"`
	Hd *bool `json:"hd,omitempty"`
	Hdr *bool `json:"hdr,omitempty"`
	Live *bool `json:"live,omitempty"`
	Location *bool `json:"location,omitempty"`
	Markdown *bool `json:"markdown,omitempty"`
	Purchased *bool `json:"purchased,omitempty"`
	Query *string `json:"query,omitempty"`
	Subtitles *bool `json:"subtitles,omitempty"`
	Type *string `json:"type,omitempty"`
	UploadDate *string `json:"upload_date,omitempty"`
	VideoSortBy *string `json:"video_sort_by,omitempty"`
	Vr180 *bool `json:"vr180,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeSearchMaxParams) GetTarget() string { return string(p.Target) }

// NewYoutubeSearchMaxParams creates a new YoutubeSearchMaxParams with the target pre-set.
func NewYoutubeSearchMaxParams() *YoutubeSearchMaxParams {
	return &YoutubeSearchMaxParams{Target: TargetYoutubeSearchMax}
}

// YoutubeSubtitlesParams contains parameters for the youtube_subtitles target.
type YoutubeSubtitlesParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	LanguageCode *string `json:"language_code,omitempty"`
	Query *string `json:"query,omitempty"`
	SubtitleOrigin *string `json:"subtitle_origin,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeSubtitlesParams) GetTarget() string { return string(p.Target) }

// NewYoutubeSubtitlesParams creates a new YoutubeSubtitlesParams with the target pre-set.
func NewYoutubeSubtitlesParams() *YoutubeSubtitlesParams {
	return &YoutubeSubtitlesParams{Target: TargetYoutubeSubtitles}
}

// YoutubeTranscriptParams contains parameters for the youtube_transcript target.
type YoutubeTranscriptParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	LanguageCode *string `json:"language_code,omitempty"`
	Query *string `json:"query,omitempty"`
	TranscriptOrigin *string `json:"transcript_origin,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeTranscriptParams) GetTarget() string { return string(p.Target) }

// NewYoutubeTranscriptParams creates a new YoutubeTranscriptParams with the target pre-set.
func NewYoutubeTranscriptParams() *YoutubeTranscriptParams {
	return &YoutubeTranscriptParams{Target: TargetYoutubeTranscript}
}

// YoutubeVideoParams contains parameters for the youtube_video target.
type YoutubeVideoParams struct {
	Target Target `json:"target"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Geo *string `json:"geo,omitempty"`
	Query *string `json:"query,omitempty"`
}

// GetTarget implements ScrapeRequest.
func (p *YoutubeVideoParams) GetTarget() string { return string(p.Target) }

// NewYoutubeVideoParams creates a new YoutubeVideoParams with the target pre-set.
func NewYoutubeVideoParams() *YoutubeVideoParams {
	return &YoutubeVideoParams{Target: TargetYoutubeVideo}
}

// TargetMeta contains metadata about a scrape target.
type TargetMeta struct {
	Group          string
	ResponseFormat string
	Parameters     []string
}

// TargetMetaMap contains metadata for all targets.
var TargetMetaMap = map[Target]TargetMeta{
	TargetAirbnb: {
		Group:          "Travel",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "markdown", "url", "xhr"},
	},
	TargetAmazon: {
		Group:          "Amazon",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "markdown", "parse", "session_id", "url", "xhr"},
	},
	TargetAmazonBestsellers: {
		Group:          "Amazon",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "category", "currency", "device_type", "domain", "geo", "markdown", "page_from", "parse", "query", "session_id", "xhr"},
	},
	TargetAmazonPricing: {
		Group:          "Amazon",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "currency", "device_type", "domain", "geo", "headless", "markdown", "page_from", "parse", "query", "session_id", "xhr"},
	},
	TargetAmazonProduct: {
		Group:          "Amazon",
		ResponseFormat: "json",
		Parameters:     []string{"autoselect_variant", "callback_url", "currency", "device_type", "domain", "geo", "headless", "markdown", "parse", "query", "session_id", "xhr"},
	},
	TargetAmazonSearch: {
		Group:          "Amazon",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "category", "currency", "device_type", "domain", "geo", "headless", "markdown", "merchant", "page_from", "parse", "query", "session_id", "sort_by", "xhr"},
	},
	TargetAmazonSellers: {
		Group:          "Amazon",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "domain", "geo", "headless", "locale", "markdown", "parse", "query", "xhr"},
	},
	TargetAppleAppStore: {
		Group:          "Marketplace",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "markdown", "url", "xhr"},
	},
	TargetAutotrader: {
		Group:          "Marketplace",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "markdown", "url", "xhr"},
	},
	TargetBbb: {
		Group:          "Business Reviews",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "markdown", "url", "xhr"},
	},
	TargetBing: {
		Group:          "Bing",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "locale", "markdown", "page_from", "parse", "session_id", "url", "xhr"},
	},
	TargetBingSearch: {
		Group:          "Bing",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "domain", "geo", "headless", "locale", "markdown", "page_count", "page_from", "parse", "query", "session_id", "xhr"},
	},
	TargetChatgpt: {
		Group:          "AI Tools",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "markdown", "parse", "prompt", "search", "xhr"},
	},
	TargetEcommerce: {
		Group:          "Other eCommerce",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "locale", "parse", "parser_type", "url"},
	},
	TargetGemini: {
		Group:          "AI Tools",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "geo", "parse", "prompt", "xhr"},
	},
	TargetGoogle: {
		Group:          "Google",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "headless", "locale", "markdown", "page_count", "parse", "session_id", "url", "xhr"},
	},
	TargetGoogleAds: {
		Group:          "Google",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "google_nfpr", "google_results_language", "google_tbm", "google_tbs", "headless", "locale", "markdown", "page_count", "page_from", "parse", "query", "session_id", "xhr"},
	},
	TargetGoogleAiMode: {
		Group:          "AI Tools",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "markdown", "parse", "query", "session_id", "xhr"},
	},
	TargetGoogleLens: {
		Group:          "Google",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "headless", "markdown", "parse", "query"},
	},
	TargetGoogleMaps: {
		Group:          "Google",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "date_range", "device_type", "geo", "google_nfpr", "google_results_language", "headless", "hotel_occupancy", "locale", "markdown", "page_from", "query", "session_id"},
	},
	TargetGoogleSearch: {
		Group:          "Google",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "google_nfpr", "google_results_language", "google_safe_search", "google_tbm", "google_tbs", "headless", "locale", "markdown", "page_count", "page_from", "parse", "query", "session_id", "xhr"},
	},
	TargetGoogleShoppingProduct: {
		Group:          "Google",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "google_results_language", "headless", "locale", "markdown", "page_from", "parse", "query", "session_id", "xhr"},
	},
	TargetGoogleShoppingSearch: {
		Group:          "Google",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "google_results_language", "google_tbs", "headless", "locale", "markdown", "page_from", "parse", "query", "session_id"},
	},
	TargetGoogleSuggest: {
		Group:          "Google",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "locale", "query", "session_id"},
	},
	TargetGoogleTravelHotels: {
		Group:          "Google",
		ResponseFormat: "html",
		Parameters:     []string{"adults", "callback_url", "children", "date_range", "device_type", "headless", "locale", "markdown", "page_from", "query", "session_id", "stars"},
	},
	TargetGoogleTrendsExplore: {
		Group:          "Google",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "date_end", "date_start", "device_type", "geo", "query", "search_type"},
	},
	TargetInstagramGraphqlProfile: {
		Group:          "Instagram",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "query"},
	},
	TargetLowesSearch: {
		Group:          "Lowe's",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "delivery_today_tomorrow", "delivery_zip", "free_delivery", "headless", "lowes_store_id", "pickup_today", "query", "user_agent_type"},
	},
	TargetMobile: {
		Group:          "Marketplace",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "markdown", "url", "xhr"},
	},
	TargetPerplexity: {
		Group:          "AI Tools",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "device_type", "geo", "markdown", "parse", "prompt", "xhr"},
	},
	TargetRedditPost: {
		Group:          "Reddit",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "geo", "locale", "url"},
	},
	TargetRedditSubreddit: {
		Group:          "Reddit",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "geo", "locale", "url"},
	},
	TargetRedditUser: {
		Group:          "Reddit",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "geo", "locale", "sort", "url"},
	},
	TargetTarget: {
		Group:          "Target",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "delivery_zip", "device_type", "headless", "target_store_id", "url", "xhr"},
	},
	TargetTargetProduct: {
		Group:          "Target",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "delivery_type", "delivery_zip", "device_type", "headless", "markdown", "parse", "product_id", "target_store_id", "xhr"},
	},
	TargetTargetSearch: {
		Group:          "Target",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "delivery_type", "delivery_zip", "device_type", "headless", "markdown", "parse", "query", "target_store_id", "xhr"},
	},
	TargetTiktok: {
		Group:          "TikTok",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "headless", "url", "user_agent_type"},
	},
	TargetTiktokPost: {
		Group:          "TikTok",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "url", "xhr"},
	},
	TargetTiktokShopProduct: {
		Group:          "TikTok",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "country", "device_type", "headless", "markdown", "product_id", "xhr"},
	},
	TargetTiktokShopSearch: {
		Group:          "TikTok",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "country", "device_type", "headless", "markdown", "query"},
	},
	TargetUniversal: {
		Group:          "Universal",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "cookies", "device_type", "force_cookies", "force_headers", "geo", "headers", "headless", "http_method", "locale", "markdown", "payload", "proxy_pool", "session_id", "successful_status_codes", "url", "xhr"},
	},
	TargetUniversalEcommerce: {
		Group:          "None",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url"},
	},
	TargetWalmart: {
		Group:          "Walmart",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "device_type", "geo", "headless", "locale", "markdown", "store_id", "url", "xhr"},
	},
	TargetWalmartProduct: {
		Group:          "Walmart",
		ResponseFormat: "html",
		Parameters:     []string{"callback_url", "delivery_zip", "fulfillment_type", "headless", "markdown", "parse", "product_id", "walmart_store_id", "xhr"},
	},
	TargetWalmartSearch: {
		Group:          "Walmart",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "delivery_zip", "fulfillment_type", "headless", "markdown", "parse", "query", "walmart_store_id"},
	},
	TargetYoutubeChannel: {
		Group:          "YouTube",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "limit", "markdown", "parse", "query"},
	},
	TargetYoutubeMetadata: {
		Group:          "YouTube",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "query"},
	},
	TargetYoutubeSearch: {
		Group:          "YouTube",
		ResponseFormat: "json",
		Parameters:     []string{"360", "3d", "4k", "callback_url", "creative_commons", "duration", "hd", "hdr", "live", "location", "purchased", "query", "subtitles", "type", "upload_date", "video_sort_by", "vr180"},
	},
	TargetYoutubeSearchMax: {
		Group:          "YouTube",
		ResponseFormat: "json",
		Parameters:     []string{"360", "3d", "4k", "callback_url", "creative_commons", "duration", "hd", "hdr", "live", "location", "markdown", "purchased", "query", "subtitles", "type", "upload_date", "video_sort_by", "vr180"},
	},
	TargetYoutubeSubtitles: {
		Group:          "YouTube",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "language_code", "query", "subtitle_origin"},
	},
	TargetYoutubeTranscript: {
		Group:          "YouTube",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "language_code", "query", "transcript_origin"},
	},
	TargetYoutubeVideo: {
		Group:          "None",
		ResponseFormat: "json",
		Parameters:     []string{"callback_url", "geo", "query"},
	},
}
